=== dorocki228/test/gameserver/src/dist/data/option_data/option_data.dtd
<!ELEMENT list (option_data)*>
<!ELEMENT option_data  (for|set|skills|triggers)*>
<!ATTLIST option_data
	id CDATA #REQUIRED>

<!ELEMENT for (set|effect)*>

		<!ELEMENT effect (def|set)*>
		<!ATTLIST effect
				enabled CDATA #IMPLIED
				name CDATA #IMPLIED
				interval CDATA #IMPLIED
				instant CDATA #IMPLIED
				value CDATA #IMPLIED
				chance CDATA #IMPLIED
				type CDATA #IMPLIED>

		<!ELEMENT def (#PCDATA)>
		<!ATTLIST def
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

<!ELEMENT set (#PCDATA)*>
<!ATTLIST set
	order CDATA #IMPLIED
	stat CDATA #IMPLIED
	value CDATA #REQUIRED>

<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED>

=== dorocki228/test/gameserver/src/dist/data/option_data/20500-20599.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "option_data.dtd">
<list>
	<option_data id="20517">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="16.999"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20518">
		<for>
			<effect name="p_magical_defence">
				<def name="p_magical_defence_param1" value="all"/>
				<def name="p_magical_defence_param2" value="13.413"/>
				<def name="p_magical_defence_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20519">
		<for>
			<effect name="p_max_hp">
				<def name="p_max_hp_param1" value="all"/>
				<def name="p_max_hp_param2" value="63.986"/>
				<def name="p_max_hp_param3" value="diff"/>
				<def name="p_max_hp_param4" value="0"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20520">
		<for>
			<effect name="p_max_mp">
				<def name="p_max_mp_param1" value="all"/>
				<def name="p_max_mp_param2" value="20.954"/>
				<def name="p_max_mp_param3" value="diff"/>
				<def name="p_max_mp_param4" value="0"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20521">
		<for>
			<effect name="p_max_cp">
				<def name="p_max_cp_param1" value="all"/>
				<def name="p_max_cp_param2" value="115.176"/>
				<def name="p_max_cp_param3" value="diff"/>
				<def name="p_max_cp_param4" value="0"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20522">
		<for>
			<effect name="p_physical_attack">
				<def name="p_physical_attack_param1" value="all"/>
				<def name="p_physical_attack_param2" value="10.734"/>
				<def name="p_physical_attack_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20523">
		<for>
			<effect name="p_magical_attack">
				<def name="p_magical_attack_param1" value="all"/>
				<def name="p_magical_attack_param2" value="13.23"/>
				<def name="p_magical_attack_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20524">
		<for>
			<effect name="p_hp_regen">
				<def name="p_hp_regen_param1" value="all"/>
				<def name="p_hp_regen_param2" value="0.29"/>
				<def name="p_hp_regen_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20525">
		<for>
			<effect name="p_mp_regen">
				<def name="p_mp_regen_param1" value="all"/>
				<def name="p_mp_regen_param2" value="0.125"/>
				<def name="p_mp_regen_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20526">
		<for>
			<effect name="p_cp_regen">
				<def name="p_cp_regen_param1" value="all"/>
				<def name="p_cp_regen_param2" value="0.294"/>
				<def name="p_cp_regen_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20527">
		<for>
			<effect name="p_avoid">
				<def name="p_avoid_param1" value="all"/>
				<def name="p_avoid_param2" value="1.467"/>
				<def name="p_avoid_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20528">
		<for>
			<effect name="p_hit">
				<def name="p_hit_param1" value="all"/>
				<def name="p_hit_param2" value="1.467"/>
				<def name="p_hit_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20529">
		<for>
			<effect name="p_critical_rate">
				<def name="p_critical_rate_param1" value="all"/>
				<def name="p_critical_rate_param2" value="11.44"/>
				<def name="p_critical_rate_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20530">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_magical_defence">
				<def name="p_magical_defence_param1" value="all"/>
				<def name="p_magical_defence_param2" value="6.191"/>
				<def name="p_magical_defence_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20531">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_max_hp">
				<def name="p_max_hp_param1" value="all"/>
				<def name="p_max_hp_param2" value="29.532"/>
				<def name="p_max_hp_param3" value="diff"/>
				<def name="p_max_hp_param4" value="0"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20532">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_max_mp">
				<def name="p_max_mp_param1" value="all"/>
				<def name="p_max_mp_param2" value="9.671"/>
				<def name="p_max_mp_param3" value="diff"/>
				<def name="p_max_mp_param4" value="0"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20533">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_max_cp">
				<def name="p_max_cp_param1" value="all"/>
				<def name="p_max_cp_param2" value="53.158"/>
				<def name="p_max_cp_param3" value="diff"/>
				<def name="p_max_cp_param4" value="0"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20534">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_physical_attack">
				<def name="p_physical_attack_param1" value="all"/>
				<def name="p_physical_attack_param2" value="4.954"/>
				<def name="p_physical_attack_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20535">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_magical_attack">
				<def name="p_magical_attack_param1" value="all"/>
				<def name="p_magical_attack_param2" value="6.106"/>
				<def name="p_magical_attack_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20536">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_hp_regen">
				<def name="p_hp_regen_param1" value="all"/>
				<def name="p_hp_regen_param2" value="0.14"/>
				<def name="p_hp_regen_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20537">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_mp_regen">
				<def name="p_mp_regen_param1" value="all"/>
				<def name="p_mp_regen_param2" value="0.058"/>
				<def name="p_mp_regen_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20538">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_cp_regen">
				<def name="p_cp_regen_param1" value="all"/>
				<def name="p_cp_regen_param2" value="0.136"/>
				<def name="p_cp_regen_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20539">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_avoid">
				<def name="p_avoid_param1" value="all"/>
				<def name="p_avoid_param2" value="0.677"/>
				<def name="p_avoid_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20540">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_hit">
				<def name="p_hit_param1" value="all"/>
				<def name="p_hit_param2" value="0.677"/>
				<def name="p_hit_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20541">
		<for>
			<effect name="p_physical_defence">
				<def name="p_physical_defence_param1" value="all"/>
				<def name="p_physical_defence_param2" value="9.153"/>
				<def name="p_physical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_critical_rate">
				<def name="p_critical_rate_param1" value="all"/>
				<def name="p_critical_rate_param2" value="5.28"/>
				<def name="p_critical_rate_param3" value="diff"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20542">
		<for>
			<effect name="p_magical_defence">
				<def name="p_magical_defence_param1" value="all"/>
				<def name="p_magical_defence_param2" value="7.222"/>
				<def name="p_magical_defence_param3" value="diff"/>
			</effect>
			<effect name="p_max_hp">
				<def name="p_max_hp_param1" value="all"/>
				<def name="p_max_hp_param2" value="29.532"/>
				<def name="p_max_hp_param3" value="diff"/>
				<def name="p_max_hp_param4" value="0"/>
			</effect>
		</for>
	</option_data>
	<option_data id="20543">
		<for>
			<effect name="p_magical_defence">
				<def name="p_magical_defence_param1" value="all"/>
