=== dorocki228/test/gameserver/dist/config/Phantom/items/armor/armor.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (PhantomSet)*>
<!ELEMENT helm EMPTY>
<!ATTLIST helm
	item_id CDATA #REQUIRED
>
<!ELEMENT gloves EMPTY>
<!ATTLIST gloves
	item_id CDATA #REQUIRED
>
<!ELEMENT gaiter EMPTY>
<!ATTLIST gaiter
	item_id CDATA #REQUIRED 
>
<!ELEMENT chest EMPTY>
<!ATTLIST chest
	item_id CDATA #REQUIRED
>
<!ELEMENT boots EMPTY>
<!ATTLIST boots
	item_id CDATA #REQUIRED
>
<!ELEMENT shield EMPTY>
<!ATTLIST shield
	item_id CDATA #REQUIRED
>
<!ELEMENT PhantomSet ((helm, chest, gaiter, gloves, boots, shield))>
<!ATTLIST PhantomSet
	class_id CDATA #REQUIRED
	grade CDATA #REQUIRED 
>

=== dorocki228/test/config/Phantom/items/armor/C/[PL_set].xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "armor.dtd">
<list>
	<PhantomSet class_id="8;9;23;24;36;37;48;17;2;127;128;135;129;130" grade="C">
		<helm item_id="2414" /> <!-- Шлем -->
		<chest item_id="398" /> <!-- Верх -->
		<gaiter item_id="418" /> <!-- Низ -->
		<gloves item_id="2455" /> <!-- Перчатки -->
		<boots item_id="2431" /> <!-- Ботинки -->
		<shield item_id="0" /> <!-- щит\сигил -->
	</PhantomSet>
 </list>
