=== dorocki228/test/data/zone/zone.dtd
<!ELEMENT list (zone)*>
<!ELEMENT zone (polygon|circle|rectangle|banned_polygon|banned_circle|banned_rectangle|map|banned_map|set|restart_point
		|PKrestart_point|outposts|in_game_name_en|in_game_name_ru)*>
<!ATTLIST zone
	name CDATA #REQUIRED
	type CDATA #REQUIRED>
<!ELEMENT polygon (coords)*>
<!ELEMENT circle (coords)*>
<!ELEMENT rectangle (coords)*>
<!ELEMENT restart_point (coords)*>
<!ELEMENT PKrestart_point (coords)*>
<!ELEMENT banned_polygon (coords)*>
<!ELEMENT banned_circle (coords)*>
<!ELEMENT banned_rectangle (coords)*>
<!ELEMENT map (#PCDATA)>
<!ATTLIST map
	value CDATA #REQUIRED>
<!ELEMENT banned_map (#PCDATA)>
<!ATTLIST banned_map
	value CDATA #REQUIRED>
<!ELEMENT coords (#PCDATA)>
<!ATTLIST coords
	loc CDATA #REQUIRED>
<!ATTLIST circle
	loc CDATA #IMPLIED>
<!ATTLIST banned_circle
	loc CDATA #IMPLIED>
<!ELEMENT outposts (outpost)*>
<!ELEMENT outpost (#PCDATA)>
<!ATTLIST outpost
		name CDATA #REQUIRED>
<!ELEMENT in_game_name_en (#PCDATA)>
<!ATTLIST in_game_name_en
		val CDATA #REQUIRED>
<!ELEMENT in_game_name_ru (#PCDATA)>
<!ATTLIST in_game_name_ru
		val CDATA #REQUIRED>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	val CDATA #REQUIRED>

=== dorocki228/test/gameserver/dist/data/zone/liberation_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "zone.dtd">
<list>
    <zone name="[liberation_fortress]" type="custom">
        <set name="enabled" val="false"/>
        <polygon>
            <coords loc="180224 -19584"/>
            <coords loc="179712 -14208"/>
            <coords loc="176128 -14080"/>
            <coords loc="175744 -19968"/>
        </polygon>
    </zone>
</list>

=== dorocki228/test/gameserver/src/dist/custom2/zone/battle_zone.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "zone.dtd">
<list>

	<zone name="[Pvpevemt]" type="battle_zone" >
		<set name="enabled" value="true"/>
		<set name="entering_message_no" value="283"/>
		<set name="leaving_message_no" value="284"/>
		<polygon>
			<coords loc="217512 73128 944 47211"/>
			<coords loc="216968 73160 928 48926"/>
			<coords loc="216840 72808 960 59707"/>
			<coords loc="216824 72392 1040 60649"/>
			<coords loc="216888 72072 1032 19870"/>
			<coords loc="216744 71608 1048 58989"/>
			<coords loc="216824 71288 1056 57314"/>
			<coords loc="216968 70856 1104 2592"/>
			<coords loc="217208 70632 1184 26394"/>
			<coords loc="217736 70920 1224 41579"/>
			<coords loc="218216 71320 1136 19912"/>
			<coords loc="218232 71848 1048 26901"/>
			<coords loc="218136 72216 1048 36393"/>
			<coords loc="217848 72984 944 42627"/>
		</polygon>
	</zone>

</list>
