=== dorocki228/test/gameserver/src/dist/data/skills/skills.dtd
<!ELEMENT list (skill)*>

	<!ELEMENT skill  (set|for|operate_cond|target_operate_cond|passive_conditions)*>
	<!ATTLIST skill
		id CDATA #REQUIRED
		level CDATA #REQUIRED
		name CDATA #REQUIRED>

		<!ELEMENT set (#PCDATA)*>
		<!ATTLIST set
			name CDATA #IMPLIED
			order CDATA #IMPLIED
			stat CDATA #IMPLIED
			value CDATA #REQUIRED>

		<!ELEMENT start_effect (def|set)*>
		<!ATTLIST start_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

		<!ELEMENT tick_effect (def|set)*>
		<!ATTLIST tick_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

		<!ELEMENT self_effect (def|set)*>
		<!ATTLIST self_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT effect (def|set)*>
		<!ATTLIST effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT pvp_effect (def|set)*>
		<!ATTLIST pvp_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT pve_effect (def|set)*>
		<!ATTLIST pve_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT end_effect (def|set)*>
		<!ATTLIST end_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

			<!ELEMENT def (#PCDATA)>
			<!ATTLIST def
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

		<!ELEMENT for (
				start_effect|tick_effect|self_effect|effect|pvp_effect|pve_effect|end_effect
				|set)*>

		<!ELEMENT operate_cond (cond)*>
		<!ATTLIST operate_cond>

		<!ELEMENT target_operate_cond (cond)*>
		<!ATTLIST target_operate_cond>

		<!ELEMENT passive_conditions (cond)*>
		<!ATTLIST passive_conditions>

		<!ELEMENT cond (def)*>
		<!ATTLIST cond
				name CDATA #IMPLIED
				value CDATA #IMPLIED>

=== dorocki228/test/gameserver/src/dist/data/skills/9500-9599.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
    <skill id="9504" level="1" name="Scroll: PK (Low-grade)">
        <set name="operate_type" value="A1"/>
        <set name="icon" value="icon.skill0000"/>
        <set name="magic_level" value="1"/>
        <set name="magic_type" value="0"/>
        <set name="special_level" value="0"/>
        <set name="magic_critical_rate" value="5"/>
        <set name="change_skill_id" value="0"/>
        <set name="is_magic" value="2"/>
        <set name="is_double" value="0"/>
        <set name="item_consume" value="35741:1"/>
        <set name="cast_range" value="-1"/>
        <set name="effective_range" value="-1"/>
        <set name="skill_hit_time" value="2.0"/>
        <set name="skill_cool_time" value="0.2"/>
        <set name="skill_hit_cancel_time" value="0.5"/>
        <set name="reuse_delay" value="3.0"/>
        <set name="attribute" value="attr_none;0"/>
        <set name="trait" value="trait_none"/>
        <set name="target_type" value="self"/>
        <set name="affect_scope" value="single"/>
        <set name="affect_limit" value="0;0"/>
        <set name="next_action" value="none"/>
        <set name="debuff" value="0"/>
        <set name="ride_state" value="ride_none;ride_strider;ride_wyvern;ride_wolf"/>
        <set name="multi_class" value="0"/>
        <set name="undeletable" value="0"/>
        <set name="olympiad_use" value="1"/>
        <operate_cond>
            <cond name="op_pkcount">
                <def name="op_pkcount_param1" value="self"/>
            </cond>
            <cond name="op_territory">
                <def name="op_territory_param1" value="{{18667;169635;-3496;0};{18462;171131;-3504;0};{15907;170795;-3544;0};{16992;169099;-3504;0}}"/>
                <def name="op_territory_param2" value="t_self"/>
            </cond>
            <cond name="op_not_cursed"/>
        </operate_cond>
        <for>
            <effect name="i_pk_count">
                <def name="i_pk_count_param1" value="-1"/>
            </effect>
        </for>
    </skill>
    <skill id="9505" level="1" name="Scroll: PK (Mid-grade)">
        <set name="operate_type" value="A1"/>
        <set name="icon" value="icon.skill0000"/>
        <set name="magic_level" value="1"/>
        <set name="magic_type" value="0"/>
        <set name="special_level" value="0"/>
        <set name="magic_critical_rate" value="5"/>
        <set name="change_skill_id" value="0"/>
        <set name="is_magic" value="2"/>
        <set name="is_double" value="0"/>
        <set name="item_consume" value="35752:1"/>
        <set name="cast_range" value="-1"/>
        <set name="effective_range" value="-1"/>
        <set name="skill_hit_time" value="2.0"/>
        <set name="skill_cool_time" value="0.2"/>
        <set name="skill_hit_cancel_time" value="0.5"/>
        <set name="reuse_delay" value="3.0"/>
        <set name="attribute" value="attr_none;0"/>
        <set name="trait" value="trait_none"/>
        <set name="target_type" value="self"/>
        <set name="affect_scope" value="single"/>
        <set name="affect_limit" value="0;0"/>
        <set name="next_action" value="none"/>
        <set name="debuff" value="0"/>
        <set name="ride_state" value="ride_none;ride_strider;ride_wyvern;ride_wolf"/>
        <set name="multi_class" value="0"/>
        <set name="undeletable" value="0"/>
        <set name="olympiad_use" value="1"/>
        <operate_cond>
            <cond name="op_pkcount">
                <def name="op_pkcount_param1" value="self"/>
            </cond>
            <cond name="op_territory">
                <def name="op_territory_param1" value="{{18667;169635;-3496;0};{18462;171131;-3504;0};{15907;170795;-3544;0};{16992;169099;-3504;0}}"/>
                <def name="op_territory_param2" value="t_self"/>
            </cond>
            <cond name="op_not_cursed"/>
        </operate_cond>
        <for>
            <effect name="i_pk_count">
                <def name="i_pk_count_param1" value="-3"/>
            </effect>
        </for>
    </skill>
    <skill id="9506" level="1" name="Scroll: PK (High-grade)">
        <set name="operate_type" value="A1"/>
        <set name="icon" value="icon.skill0000"/>
        <set name="magic_level" value="1"/>
        <set name="magic_type" value="0"/>
        <set name="special_level" value="0"/>
        <set name="magic_critical_rate" value="5"/>
        <set name="change_skill_id" value="0"/>
        <set name="is_magic" value="2"/>
        <set name="is_double" value="0"/>
        <set name="item_consume" value="35753:1"/>
        <set name="cast_range" value="-1"/>
        <set name="effective_range" value="-1"/>
        <set name="skill_hit_time" value="2.0"/>
        <set name="skill_cool_time" value="0.2"/>
        <set name="skill_hit_cancel_time" value="0.5"/>
        <set name="reuse_delay" value="3.0"/>
        <set name="attribute" value="attr_none;0"/>
        <set name="trait" value="trait_none"/>
        <set name="target_type" value="self"/>
        <set name="affect_scope" value="single"/>
        <set name="affect_limit" value="0;0"/>
        <set name="next_action" value="none"/>
        <set name="debuff" value="0"/>
        <set name="ride_state" value="ride_none;ride_strider;ride_wyvern;ride_wolf"/>
        <set name="multi_class" value="0"/>
        <set name="undeletable" value="0"/>
        <set name="olympiad_use" value="1"/>
        <operate_cond>
            <cond name="op_pkcount">
                <def name="op_pkcount_param1" value="self"/>
            </cond>
            <cond name="op_territory">
                <def name="op_territory_param1" value="{{18667;169635;-3496;0};{18462;171131;-3504;0};{15907;170795;-3544;0};{16992;169099;-3504;0}}"/>
                <def name="op_territory_param2" value="t_self"/>
            </cond>
            <cond name="op_not_cursed"/>
        </operate_cond>
        <for>
            <effect name="i_pk_count">
                <def name="i_pk_count_param1" value="-5"/>
            </effect>
        </for>
    </skill>
    <skill id="9507" level="1" name="Scroll: PK (Top-grade)">
        <set name="operate_type" value="A1"/>
        <set name="icon" value="icon.skill0000"/>
        <set name="magic_level" value="1"/>
        <set name="magic_type" value="0"/>
        <set name="special_level" value="0"/>
        <set name="magic_critical_rate" value="5"/>
        <set name="change_skill_id" value="0"/>
        <set name="is_magic" value="2"/>
        <set name="is_double" value="0"/>
        <set name="item_consume" value="35754:1"/>
        <set name="cast_range" value="-1"/>
        <set name="effective_range" value="-1"/>
        <set name="skill_hit_time" value="2.0"/>
        <set name="skill_cool_time" value="0.2"/>
        <set name="skill_hit_cancel_time" value="0.5"/>
        <set name="reuse_delay" value="3.0"/>
        <set name="attribute" value="attr_none;0"/>
        <set name="trait" value="trait_none"/>
        <set name="target_type" value="self"/>
        <set name="affect_scope" value="single"/>
        <set name="affect_limit" value="0;0"/>
        <set name="next_action" value="none"/>
        <set name="debuff" value="0"/>
        <set name="ride_state" value="ride_none;ride_strider;ride_wyvern;ride_wolf"/>
        <set name="multi_class" value="0"/>
        <set name="undeletable" value="0"/>
        <set name="olympiad_use" value="1"/>
        <operate_cond>
            <cond name="op_pkcount">
                <def name="op_pkcount_param1" value="self"/>
            </cond>
            <cond name="op_territory">
                <def name="op_territory_param1" value="{{18667;169635;-3496;0};{18462;171131;-3504;0};{15907;170795;-3544;0};{16992;169099;-3504;0}}"/>
                <def name="op_territory_param2" value="t_self"/>
            </cond>
            <cond name="op_not_cursed"/>
        </operate_cond>
        <for>
            <effect name="i_pk_count">
                <def name="i_pk_count_param1" value="-10"/>
            </effect>
        </for>
    </skill>
</list>

=== dorocki228/test/gameserver/src/dist/data/skills/23100-23199.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
    <skill id="23174" level="1" name="Soul Stealth">
        <set name="operate_type" value="A2"/>
        <set name="icon" value="icon.skill_agathion_special"/>
        <set name="magic_level" value="-1"/>
        <set name="magic_type" value="1"/>
        <set name="special_level" value="-1"/>
        <set name="magic_critical_rate" value="-5"/>
        <set name="change_skill_id" value="0"/>
        <set name="is_magic" value="2"/>
        <set name="is_double" value="0"/>
        <set name="cast_range" value="600"/>
        <set name="effective_range" value="600"/>
        <set name="skill_hit_time" value="3.0"/>
        <set name="reuse_delay" value="43200.0"/>
        <set name="reuse_delay_lock" value="1"/>
        <set name="activate_rate" value="-1"/>
        <set name="basic_property" value="none"/>
        <set name="abnormal_time" value="1800"/>
        <set name="abnormal_lv" value="26"/>
        <set name="abnormal_type" value="resurrection_special"/>
        <set name="irreplaceable_buff" value="1"/>
        <set name="buff_protect_level" value="1"/>
        <set name="attribute" value="attr_none;0"/>
        <set name="trait" value="trait_none"/>
        <set name="effect_point" value="1"/>
        <set name="target_type" value="self"/>
        <set name="affect_scope" value="single"/>
        <set name="affect_limit" value="0;0"/>
        <set name="next_action" value="none"/>
        <set name="debuff" value="0"/>
        <set name="ride_state" value="ride_none;ride_strider;ride_wyvern;ride_wolf"/>
        <set name="multi_class" value="0"/>
        <set name="undeletable" value="0"/>
        <set name="olympiad_use" value="0"/>
        <operate_cond>
            <cond name="op_need_agathion"/>
        </operate_cond>
        <for>
            <effect name="p_resurrection_special">
                <def name="p_resurrection_special_param1" value="100"/>
                <def name="p_resurrection_special_param2" value="100"/>
                <def name="p_resurrection_special_param3" value="100"/>
                <def name="p_resurrection_special_param4" value="11786:1"/>
            </effect>
        </for>
    </skill>
</list>

=== dorocki228/test/gameserver/src/dist/data/skills/54100-54199.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
    <skill id="54100" level="1" name="Sayha's Shield">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1040"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54101" level="1" name="Sayha's Magic Barrier">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1036"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54103" level="1" name="Sayha's Decrease Weight">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1257"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54104" level="1" name="Sayha's Berserker Spirit">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1062"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54105" level="1" name="Sayha's Wind Walk">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1204"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54106" level="1" name="Sayha's Might">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1068"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54108" level="1" name="Sayha's Focus">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1077"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54109" level="1" name="Sayha's Haste">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1086"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54110" level="1" name="Sayha's Death Whisper">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1242"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54111" level="1" name="Sayha's Empower">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1059"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54112" level="1" name="Sayha's Clarity">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1397"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54113" level="1" name="Sayha's Wild Magic">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1303"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54114" level="1" name="Sayha's Acumen">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1085"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54115" level="1" name="Sayha's Concentration">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1078"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54116" level="1" name="Sayha's Prophecy">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill5074"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54117" level="1" name="Sayha's Restore HP">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill0211"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
    <skill id="54118" level="1" name="Sayha's Restore MP">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill0213"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="reuse_delay" value="2.0"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
</list>

=== dorocki228/test/gameserver/src/dist/data/skills/32600-32699.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
    <skill id="32663" level="1" name="Test Barrier - 5 HP and 1 Limit">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill11621"/>
        <set name="skill_cool_time" value="0.5"/>
        <set name="skill_hit_time" value="0.5"/>
        <set name="cast_range" value="-1"/>
        <set name="debuff" value="0"/>
    </skill>
</list>

=== dorocki228/test/gameserver/src/dist/data/skills/19100-19199.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
    <skill id="19113" level="1" name="No Clan Return">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill_recall"/>
        <set name="skill_hit_time" value="2.0"/>
        <set name="reuse_delay" value="1800.0"/>
        <set name="cast_range" value="600"/>
        <set name="effect_point" value="-100"/>
        <set name="debuff" value="1"/>
    </skill>
    <skill id="19114" level="1" name="No Clan Resurrection">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill_resurrection"/>
        <set name="skill_cool_time" value="0.5"/>
        <set name="skill_hit_time" value="2.0"/>
        <set name="reuse_delay" value="1800.0"/>
        <set name="cast_range" value="600"/>
        <set name="effect_point" value="-100"/>
        <set name="debuff" value="1"/>
    </skill>
    <skill id="19119" level="1" name="Noblesse Grace">
        <!--TODO: Notdone-->
        <set name="operate_type" value="P"/>
        <set name="icon" value="icon.skill1323"/>
        <set name="skill_hit_time" value="4.0"/>
        <set name="cast_range" value="-1"/>
        <set name="effect_point" value="1"/>
        <set name="debuff" value="0"/>
    </skill>
</list>
