=== dorocki228/test/gameserver/src/dist/data/upgrade_system/upgrade_system.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT list (normal_upgrade|rare_upgrade)*>

	<!ELEMENT normal_upgrade (required_items|results|unk_data)*>
	<!ATTLIST normal_upgrade
		id CDATA #REQUIRED
		type CDATA #REQUIRED
		item_id CDATA #REQUIRED
		enchant_level CDATA #IMPLIED
		price CDATA #IMPLIED
		unk CDATA #IMPLIED>

		<!ELEMENT required_items (item)*>

			<!ELEMENT item (#PCDATA)>
			<!ATTLIST item
				id CDATA #REQUIRED
				count CDATA #REQUIRED
				enchant CDATA #IMPLIED>

		<!ELEMENT results (success|fail|bonus)*>

			<!ELEMENT success (item)*>
			<!ATTLIST success
				chance CDATA #REQUIRED>

			<!ELEMENT fail (item)*>
			<!ATTLIST fail
				chance CDATA #REQUIRED>

			<!ELEMENT bonus (item)*>
			<!ATTLIST bonus
				chance CDATA #REQUIRED>

		<!ELEMENT unk_data (unk)*>

			<!ELEMENT unk (#PCDATA)>
			<!ATTLIST unk
				value CDATA #REQUIRED>

	<!ELEMENT rare_upgrade (required_items|result_item|unk_data)*>
	<!ATTLIST rare_upgrade
		id CDATA #REQUIRED
		item_id CDATA #REQUIRED
		enchant_level CDATA #IMPLIED
		price CDATA #IMPLIED
		unk CDATA #IMPLIED>

		<!ELEMENT result_item (#PCDATA)>
		<!ATTLIST result_item
			id CDATA #REQUIRED
			count CDATA #IMPLIED
			enchant CDATA #IMPLIED>

=== dorocki228/test/gameserver/src/dist/data/upgrade_system/normal/1700-1799.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "upgrade_system.dtd">
<!--AUTHOR: Bonux-->
<list>
	<normal_upgrade id="1700" type="1" item_id="2585" enchant_level="31" price="2117000000">	<!--Katana*Caliburs-->
		<required_items>
			<item id="1460" count="470444"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="1059"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="30"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1701" type="1" item_id="2585" enchant_level="32" price="84680000">	<!--Katana*Caliburs-->
		<required_items>
			<item id="1460" count="526898"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="1186"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="31"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1706" type="1" item_id="2586" enchant_level="13" price="127020000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="28227"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="64"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="12"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1707" type="1" item_id="2586" enchant_level="14" price="169360000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="37636"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="85"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="13"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1708" type="1" item_id="2586" enchant_level="15" price="211700000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="47044"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="106"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="14"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1709" type="1" item_id="2586" enchant_level="16" price="254040000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="56453"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="127"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="15"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1710" type="1" item_id="2586" enchant_level="17" price="296380000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="65862"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="148"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="16"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1711" type="1" item_id="2586" enchant_level="18" price="338720000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="75271"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="169"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="17"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1712" type="1" item_id="2586" enchant_level="19" price="381060000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="84680"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="191"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="18"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1713" type="1" item_id="2586" enchant_level="20" price="423400000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="94089"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="212"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="19"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1714" type="1" item_id="2586" enchant_level="21" price="508080000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="112907"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="254"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="20"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1715" type="1" item_id="2586" enchant_level="22" price="592760000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="131724"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="296"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="21"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1716" type="1" item_id="2586" enchant_level="23" price="677440000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="150542"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="339"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="22"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1717" type="1" item_id="2586" enchant_level="24" price="762120000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="169360"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="381"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="23"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1718" type="1" item_id="2586" enchant_level="25" price="931480000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="206996"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="466"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="24"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1719" type="1" item_id="2586" enchant_level="26" price="1100840000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="244631"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="550"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="25"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1720" type="1" item_id="2586" enchant_level="27" price="1270200000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="282267"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="635"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="26"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1721" type="1" item_id="2586" enchant_level="28" price="1439560000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="319902"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="720"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="27"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1722" type="1" item_id="2586" enchant_level="29" price="1608920000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="357538"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="804"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="28"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1723" type="1" item_id="2586" enchant_level="30" price="1862960000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="413991"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="931"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="29"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1724" type="1" item_id="2586" enchant_level="31" price="2117000000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="470444"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="1059"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
			<success chance="100">
				<item id="2626" count="1" enchant="30"/>	<!--Samurai Long Sword*Samurai Long Sword-->
			</success>
		</results>
	</normal_upgrade>
	<normal_upgrade id="1725" type="1" item_id="2586" enchant_level="32" price="84680000">	<!--Katana*Ultimate Sword-->
		<required_items>
			<item id="1460" count="526898"/>	<!--Crystal (B-grade)-->
			<item id="91530" count="1186"/>	<!--Weapon Polish (B-grade)-->
		</required_items>
		<results>
