=== dorocki228/test/config/gve_rewards.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (item|level|pvp|set|enchant|noble|hero|title_color)*>

<!ELEMENT item EMPTY>
<!ATTLIST item
  adena CDATA #REQUIRED
  exp CDATA #REQUIRED
  id CDATA #REQUIRED
  sp CDATA #REQUIRED>

<!ELEMENT level EMPTY>
<!ATTLIST level
  adena CDATA #REQUIRED
  exp CDATA #REQUIRED
  lvl CDATA #REQUIRED
  sp CDATA #REQUIRED>

<!ELEMENT pvp EMPTY>
<!ATTLIST pvp
  adena CDATA #REQUIRED
  count CDATA #REQUIRED
  exp CDATA #REQUIRED
  sp CDATA #REQUIRED>
  
<!ELEMENT set EMPTY>
<!ATTLIST set
  adena CDATA #REQUIRED
  exp CDATA #REQUIRED
  chest CDATA #REQUIRED
  sp CDATA #REQUIRED>
  
<!ELEMENT enchant EMPTY>
<!ATTLIST enchant
  slot CDATA #REQUIRED
  grade CDATA #REQUIRED
  value CDATA #REQUIRED
  adena CDATA #REQUIRED
  exp CDATA #REQUIRED
  sp CDATA #REQUIRED>
  
<!ELEMENT noble EMPTY>
<!ATTLIST noble
  adena CDATA #REQUIRED
  exp CDATA #REQUIRED
  sp CDATA #REQUIRED>
  
<!ELEMENT hero EMPTY>
<!ATTLIST hero
  adena CDATA #REQUIRED
  exp CDATA #REQUIRED
  sp CDATA #REQUIRED>
  
<!ELEMENT title_color EMPTY>
<!ATTLIST title_color
  reward CDATA #REQUIRED
  color CDATA #REQUIRED>

=== dorocki228/test/config/gve_rewards.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "gve_rewards.dtd">
<list>
    <!--  Armor & Weapon & Jewell Each Piece  -->
    <!--  C-grade Weapon -->
    <item id="226" exp="0" sp="0" adena="1"/>
    <item id="75" exp="0" sp="0" adena="1"/>
    <item id="76" exp="0" sp="0" adena="1"/>
    <item id="77" exp="0" sp="0" adena="1"/>
    <item id="134" exp="0" sp="0" adena="1"/>
    <item id="162" exp="0" sp="0" adena="1"/>
    <item id="231" exp="0" sp="0" adena="1"/>
    <item id="233" exp="0" sp="0" adena="1"/>
    <item id="265" exp="0" sp="0" adena="1"/>
    <item id="283" exp="0" sp="0" adena="1"/>
    <item id="197" exp="0" sp="0" adena="1"/>
    <item id="199" exp="0" sp="0" adena="1"/>
    <item id="200" exp="0" sp="0" adena="1"/>
    <item id="132" exp="0" sp="0" adena="1"/>
    <item id="145" exp="0" sp="0" adena="1"/>
    <item id="84" exp="0" sp="0" adena="1"/>
    <item id="196" exp="0" sp="0" adena="1"/>
    <item id="174" exp="0" sp="0" adena="1"/>
    <item id="201" exp="0" sp="0" adena="1"/>
    <item id="202" exp="0" sp="0" adena="1"/>
    <item id="198" exp="0" sp="0" adena="1"/>
    <item id="95" exp="0" sp="0" adena="1"/>
    <item id="7898" exp="0" sp="0" adena="1"/>
    <item id="286" exp="0" sp="0" adena="1"/>
    <item id="266" exp="0" sp="0" adena="1"/>
    <item id="299" exp="0" sp="0" adena="1"/>
    <item id="2503" exp="0" sp="0" adena="1"/>
    <item id="204" exp="0" sp="0" adena="1"/>
    <item id="205" exp="0" sp="0" adena="1"/>
    <item id="206" exp="0" sp="0" adena="1"/>
    <item id="135" exp="0" sp="0" adena="1"/>
    <item id="5286" exp="0" sp="0" adena="1"/>
    <item id="7888" exp="0" sp="0" adena="1"/>
    <item id="7897" exp="0" sp="0" adena="1"/>
    <item id="7891" exp="0" sp="0" adena="1"/>
    <item id="228" exp="0" sp="0" adena="1"/>
    <item id="230" exp="0" sp="0" adena="1"/>
    <item id="2572" exp="0" sp="0" adena="2"/>
    <!-- [shamshir*shamshir] -->
    <item id="2573" exp="0" sp="0" adena="2"/>
    <!-- [shamshir*katana] -->
    <item id="2574" exp="0" sp="0" adena="2"/>
    <!-- [shamshir*spirits_sword] -->
    <item id="2575" exp="0" sp="0" adena="2"/>
    <!-- [shamshir*raid_sword] -->
    <item id="2582" exp="0" sp="0" adena="2"/>
    <!-- [katana*katana] -->
    <item id="2583" exp="0" sp="0" adena="2"/>
    <!-- [katana*spirits_sword] -->
    <item id="2584" exp="0" sp="0" adena="2"/>
    <!-- [katana*raid_sword] -->
    <item id="2591" exp="0" sp="0" adena="2"/>
    <!-- [spirits_sword*spirits_sword] -->
    <item id="2592" exp="0" sp="0" adena="2"/>
    <!-- [spirits_sword*raid_sword] -->
    <item id="2599" exp="0" sp="0" adena="2"/>
    <!-- [raid_sword*raid_sword] -->
    <!--  B-grade Weapon -->
    <item id="142" exp="0" sp="0" adena="3"/>
    <item id="78" exp="0" sp="0" adena="3"/>
    <item id="91" exp="0" sp="0" adena="3"/>
    <item id="229" exp="0" sp="0" adena="3"/>
    <item id="243" exp="0" sp="0" adena="3"/>
    <item id="267" exp="0" sp="0" adena="3"/>
    <item id="284" exp="0" sp="0" adena="3"/>
    <item id="300" exp="0" sp="0" adena="3"/>
    <item id="92" exp="0" sp="0" adena="3"/>
    <item id="148" exp="0" sp="0" adena="3"/>
    <item id="243" exp="0" sp="0" adena="3"/>
    <item id="7892" exp="0" sp="0" adena="3"/>
    <item id="79" exp="0" sp="0" adena="3"/>
    <item id="171" exp="0" sp="0" adena="3"/>
    <item id="175" exp="0" sp="0" adena="3"/>
    <item id="268" exp="0" sp="0" adena="3"/>
    <item id="287" exp="0" sp="0" adena="3"/>
    <item id="97" exp="0" sp="0" adena="3"/>
    <item id="210" exp="0" sp="0" adena="3"/>
    <item id="7883" exp="0" sp="0" adena="3"/>
    <item id="7889" exp="0" sp="0" adena="3"/>
    <item id="7901" exp="0" sp="0" adena="3"/>
    <item id="7893" exp="0" sp="0" adena="3"/>
    <item id="234" exp="0" sp="0" adena="3"/>
    <item id="2571" exp="0" sp="0" adena="4"/>
    <!-- [stormbringer*samurai_longsword]  -->
    <item id="2606" exp="0" sp="0" adena="4"/>
    <!-- [caliburs*caliburs]  -->
    <item id="2607" exp="0" sp="0" adena="4"/>
    <!-- [caliburs*sword_of_limit]  -->
    <item id="2608" exp="0" sp="0" adena="4"/>
    <!-- [caliburs*sword_of_delusion]  -->
    <item id="2609" exp="0" sp="0" adena="4"/>
    <!-- [caliburs*sword_of_nightmare]  -->
    <item id="2610" exp="0" sp="0" adena="4"/>
    <!-- [caliburs*tsurugi]  -->
    <item id="2612" exp="0" sp="0" adena="4"/>
    <!-- [sword_of_limit*sword_of_limit]  -->
    <item id="2613" exp="0" sp="0" adena="4"/>
    <!-- [sword_of_limit*sword_of_delusion]  -->
    <item id="2614" exp="0" sp="0" adena="4"/>
    <!-- [sword_of_limit*sword_of_nightmare]  -->
    <item id="2615" exp="0" sp="0" adena="4"/>
    <!-- [sword_of_limit*tsurugi]  -->
    <item id="2617" exp="0" sp="0" adena="4"/>
    <!-- [sword_of_delusion*sword_of_delusion]  -->
    <item id="2618" exp="0" sp="0" adena="4"/>
    <!-- [sword_of_delusion*sword_of_nightmare]  -->
    <item id="2619" exp="0" sp="0" adena="4"/>
    <!-- [sword_of_delusion*tsurugi]  -->
    <item id="2621" exp="0" sp="0" adena="4"/>
    <!-- [sword_of_nightmare*sword_of_nightmare]  -->
    <item id="2622" exp="0" sp="0" adena="4"/>
    <!-- [sword_of_nightmare*tsurugi]  -->
    <item id="2624" exp="0" sp="0" adena="4"/>
    <!-- [tsurugi*tsurugi]  -->
    <item id="2626" exp="0" sp="0" adena="4"/>
    <!-- [samurai_longsword*samurai_longsword]  -->
    <!--  A-grade Weapon -->
    <item id="269" exp="0" sp="0" adena="7"/>
    <!-- [blood_tornado] -->
    <item id="270" exp="0" sp="0" adena="7"/>
    <!-- [dragon_grinder] -->
    <item id="235" exp="0" sp="0" adena="5"/>
    <!-- [bloody_orchid] -->
    <item id="236" exp="0" sp="0" adena="5"/>
    <!-- [soul_separator] -->
    <item id="80" exp="0" sp="0" adena="5"/>
    <!-- [tallum_blade] -->
    <item id="2500" exp="0" sp="0" adena="5"/>
    <!-- [dark_legion_s_edge] -->
    <item id="7884" exp="0" sp="0" adena="7"/>
    <!-- [inferno_master] -->
    <item id="81" exp="0" sp="0" adena="7"/>
    <!-- [dragon_slayer] -->
    <item id="150" exp="0" sp="0" adena="5"/>
    <!-- [elemental_sword] -->
    <item id="7894" exp="0" sp="0" adena="5"/>
    <!-- [eye_of_soul] -->
    <item id="7895" exp="0" sp="0" adena="5"/>
    <!-- [dragon_flame_head] -->
    <item id="151" exp="0" sp="0" adena="5"/>
    <!-- [sword_of_miracle] -->
    <item id="212" exp="0" sp="0" adena="7"/>
    <!-- [dasparion_s_staff] -->
    <item id="2504" exp="0" sp="0" adena="5"/>
    <!-- [meteor_shower] -->
    <item id="164" exp="0" sp="0" adena="5"/>
    <!-- [elysian] -->
    <item id="7899" exp="0" sp="0" adena="7"/>
    <!-- [hammer_of_destroyer] -->
    <item id="7902" exp="0" sp="0" adena="7"/>
    <!-- [doom_crusher] -->
    <item id="98" exp="0" sp="0" adena="7"/>
    <!-- [halbard] -->
    <item id="305" exp="0" sp="0" adena="7"/>
    <!-- [tallum_glaive] -->
    <item id="288" exp="0" sp="0" adena="7"/>
    <!-- [carnium_bow] -->
    <item id="289" exp="0" sp="0" adena="7"/>
    <!-- [soul_bow] -->
    <item id="8678" exp="0" sp="0" adena="5"/>
    <!-- [sirra_s_blade] -->
    <item id="8679" exp="0" sp="0" adena="7"/>
    <!-- [sword_of_ipos] -->
    <item id="8680" exp="0" sp="0" adena="5"/>
    <!-- [barakiel_s_axe] -->
    <item id="8681" exp="0" sp="0" adena="7"/>
    <!-- [behemoth_s_tuning_fork] -->
    <item id="8682" exp="0" sp="0" adena="5"/>
    <!-- [naga_storm] -->
    <item id="8683" exp="0" sp="0" adena="7"/>
    <!-- [tiphon_s_spear] -->
    <item id="8684" exp="0" sp="0" adena="7"/>
    <!-- [shyeed_s_bow] -->
    <item id="8685" exp="0" sp="0" adena="7"/>
    <!-- [sobekk_s_hurricane] -->
    <item id="8686" exp="0" sp="0" adena="5"/>
    <!-- [themis_tongue] -->
    <item id="8687" exp="0" sp="0" adena="5"/>
    <!-- [cabrio_s_hand] -->
    <item id="8688" exp="0" sp="0" adena="7"/>
    <!-- [daimon_crystal] -->
    <item id="5233" exp="0" sp="0" adena="7"/>
    <!-- [kshanberk*kshanberk] -->
    <item id="5705" exp="0" sp="0" adena="7"/>
    <!-- [kshanberk*sword_of_damascus] -->
    <item id="5706" exp="0" sp="0" adena="7"/>
    <!-- [sword_of_damascus*sword_of_damascus] -->
    <item id="8938" exp="0" sp="0" adena="7"/>
    <!-- [damascus_*_tallum_blade1] -->
    <!--  Shields All Grade`s  -->
    <item id="631" exp="0" sp="0" adena="1"/>
    <!-- [eldarace_c] -->
    <item id="2497" exp="0" sp="0" adena="1"/>
    <!-- [full_plate_shield] -->
    <item id="103" exp="0" sp="0" adena="1"/>
    <!-- [tower_shield_c] -->
    <item id="107" exp="0" sp="0" adena="1"/>
    <!-- [compound_shield_c] -->
    <item id="673" exp="0" sp="0" adena="1"/>
    <!-- [avadone_shield_b] -->
    <item id="633" exp="0" sp="0" adena="1"/>
    <!-- [zubeis_shield_b] -->
    <item id="110" exp="0" sp="0" adena="1"/>
    <!-- [doom_shield_b] -->
    <item id="2498" exp="0" sp="0" adena="2"/>
    <!-- [shield_of_nightmare_a]  -->
    <item id="641" exp="0" sp="0" adena="2"/>
    <!-- [dark_crystal_shield_a]  -->
    <!--  Jewel Parts C-grade  -->
    <item id="888" exp="0" sp="0" adena="1"/>
    <item id="919" exp="0" sp="0" adena="1"/>
    <item id="857" exp="0" sp="0" adena="1"/>
    <!--  Low Set  -->
    <item id="885" exp="0" sp="0" adena="1"/>
    <item id="853" exp="0" sp="0" adena="1"/>
    <item id="917" exp="0" sp="0" adena="1"/>
    <!--  Blessed Set  -->
    <!--  Jewel Parts B-grade  -->
    <item id="864" exp="0" sp="0" adena="2"/>
    <item id="895" exp="0" sp="0" adena="2"/>
    <item id="926" exp="0" sp="0" adena="2"/>
    <!--  Black Ore Set  -->
    <!--  Jewel Parts A-grade  -->
    <item id="862" exp="0" sp="0" adena="3"/>
    <!-- [majestic_earing]  -->
    <item id="924" exp="0" sp="0" adena="3"/>
    <!-- [majestic_3]  -->
    <item id="893" exp="0" sp="0" adena="3"/>
    <!-- [majestic_ring]  -->
    <item id="871" exp="0" sp="0" adena="3"/>
    <!-- [phoenix_s_earing]  -->
    <item id="933" exp="0" sp="0" adena="3"/>
    <!-- [phoenix_s_3]  -->
    <item id="902" exp="0" sp="0" adena="3"/>
    <!-- [phoenix_s_ring]  -->
