=== dorocki228/test/gameserver/dist/data/spawn/spawn.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (spawn|territory)*>
<!ELEMENT spawn (territory|npc)*>
<!ATTLIST spawn
	name CDATA #IMPLIED
	group CDATA #IMPLIED
	territory CDATA #IMPLIED
	banned_territory CDATA #IMPLIED
	period_of_day CDATA #IMPLIED>
<!ELEMENT territory (add|rectangle|circle)*>
<!ATTLIST territory
	name CDATA #IMPLIED>
<!ELEMENT banned_territory (add)*>
<!ELEMENT add (#PCDATA)>
<!ATTLIST add
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED>
<!ELEMENT npc (set)*>
<!ATTLIST npc
	id CDATA #REQUIRED
	respawn CDATA #IMPLIED
	count CDATA #IMPLIED
	respawn_random CDATA #IMPLIED
	pos CDATA #IMPLIED
	max CDATA #IMPLIED>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT rectangle (#PCDATA)>
<!ATTLIST rectangle
	x1 CDATA #REQUIRED
	y1 CDATA #REQUIRED
	x2 CDATA #REQUIRED
	y2 CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED>
<!ELEMENT circle (#PCDATA)>
<!ATTLIST circle
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED
	radius CDATA #REQUIRED>

=== dorocki228/test/data/spawn/Ketra_Village.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>

	<!--Ketra Village -->
	<spawn group="kv_fire_post_1" name="kv_fire_post">

		<npc id="40031" count="1" respawn="600" pos="135944 -78920 -4024 0" />	<!--Пост огня -->
		<npc id="40035" count="1" respawn="60" pos="136244 -78920 -4024 0" />	<!--Гвард -->
		<npc id="40035" count="1" respawn="60" pos="136094 -78660 -4024 10917" />	<!--Гвард -->
		<npc id="40035" count="1" respawn="60" pos="135794 -78660 -4024 21833" />	<!--Гвард -->
		<npc id="40035" count="1" respawn="60" pos="135644 -78920 -4024 32750" />	<!--Гвард -->
		<npc id="40035" count="1" respawn="60" pos="135794 -79180 -4024 43667" />	<!--Гвард -->
		<npc id="40035" count="1" respawn="60" pos="136094 -79180 -4024 54583" />	<!--Гвард -->

		<!--<npc id="40031" count="1" respawn="600" pos="140696 -77080 -4688 0" />	&lt;!&ndash;Пост огня &ndash;&gt;
		<npc id="40035" count="1" respawn="60" pos="140946 -77080 -4688 0" />	&lt;!&ndash;Гвард &ndash;&gt;
		<npc id="40035" count="1" respawn="60" pos="140821 -76863 -4688 10917" />	&lt;!&ndash;Гвард &ndash;&gt;
		<npc id="40035" count="1" respawn="60" pos="140571 -76863 -4688 21833" />	&lt;!&ndash;Гвард &ndash;&gt;
		<npc id="40035" count="1" respawn="60" pos="140446 -77080 -4688 32750" />	&lt;!&ndash;Гвард &ndash;&gt;
		<npc id="40035" count="1" respawn="60" pos="140571 -77297 -4688 43667" />	&lt;!&ndash;Гвард &ndash;&gt;
		<npc id="40035" count="1" respawn="60" pos="140821 -77297 -4688 54583" />	&lt;!&ndash;Гвард &ndash;&gt;-->

		<npc id="40005" count="1" respawn="60" pos="135864 -78808 -4016 0" />	<!--Баффер -->
		<npc id="40032" count="1" respawn="60" pos="135992 -79032 -4016 0" />	<!--Капитан -->

        <!--<npc id="40005" count="1" respawn="60" pos="140744 -77176 -4704 0" />	&lt;!&ndash;Баффер &ndash;&gt;
        <npc id="40032" count="1" respawn="60" pos="140712 -77000 -4672 0" />	&lt;!&ndash;Капитан &ndash;&gt;-->

        <npc id="40035" count="1" respawn="60" pos="136294 -78920 -4024 0"/>    <!--Гвард -->
        <npc id="40035" count="1" respawn="60" pos="136119 -78617 -4024 10917"/>    <!--Гвард -->
        <npc id="40035" count="1" respawn="60" pos="135769 -78617 -4024 21833"/>    <!--Гвард -->
        <npc id="40035" count="1" respawn="60" pos="135594 -78920 -4024 32750"/>    <!--Гвард -->
        <npc id="40035" count="1" respawn="60" pos="135769 -79223 -4024 43667"/>    <!--Гвард -->
        <npc id="40035" count="1" respawn="60" pos="136119 -79223 -4024 54583"/>    <!--Гвард -->

        <npc id="42000" count="1" respawn="60" pos="136031 -78902 -4024 5065"/>    <!--Гвард -->
        <npc id="42000" count="1" respawn="60" pos="135864 -78924 -4008 78"/>    <!--Гвард -->

        <!--<npc id="40035" count="1" respawn="60" pos="141046 -77080 -4688 0" />	&lt;!&ndash;Гвард &ndash;&gt;
        <npc id="40035" count="1" respawn="60" pos="140871 -76777 -4688 10917" />	&lt;!&ndash;Гвард &ndash;&gt;
        <npc id="40035" count="1" respawn="60" pos="140521 -76777 -4688 21833" />	&lt;!&ndash;Гвард &ndash;&gt;
        <npc id="40035" count="1" respawn="60" pos="140346 -77080 -4688 32750" />	&lt;!&ndash;Гвард &ndash;&gt;
        <npc id="40035" count="1" respawn="60" pos="140521 -77383 -4688 43667" />	&lt;!&ndash;Гвард &ndash;&gt;
        <npc id="40035" count="1" respawn="60" pos="140871 -77383 -4688 54583" />	&lt;!&ndash;Гвард &ndash;&gt;-->
    </spawn>

	<spawn group="kv_water_post_1" name="kv_water_post">
		<npc id="40038" count="1" respawn="600" pos="145464 -70456 -4080 0" />	<!--Пост воды -->
		<npc id="40042" count="1" respawn="60" pos="145714 -70456 -4080 0" />	<!--Гвард -->
		<npc id="40042" count="1" respawn="60" pos="145589 -70239 -4080 10917" />	<!--Гвард -->
		<npc id="40042" count="1" respawn="60" pos="145339 -70239 -4080 21833" />	<!--Гвард -->
		<npc id="40042" count="1" respawn="60" pos="145214 -70456 -4080 32750" />	<!--Гвард -->
		<npc id="40042" count="1" respawn="60" pos="145339 -70673 -4080 43667" />	<!--Гвард -->
		<npc id="40042" count="1" respawn="60" pos="145589 -70673 -4080 54583" />	<!--Гвард -->

        <npc id="40005" count="1" respawn="60" pos="145480 -70552 -4080 0"/>    <!--Баффер -->
        <npc id="40039" count="1" respawn="60" pos="145480 -70360 -4072 0"/>    <!--Капитан -->

        <npc id="40042" count="1" respawn="60" pos="145814 -70456 -4080 0"/>    <!--Гвард -->
        <npc id="40042" count="1" respawn="60" pos="145639 -70153 -4080 10917"/>    <!--Гвард -->
        <npc id="40042" count="1" respawn="60" pos="145289 -70153 -4080 21833"/>    <!--Гвард -->
        <npc id="40042" count="1" respawn="60" pos="145114 -70456 -4080 32750"/>    <!--Гвард -->
        <npc id="40042" count="1" respawn="60" pos="145289 -70759 -4080 43667"/>    <!--Гвард -->
        <npc id="40042" count="1" respawn="60" pos="145639 -70759 -4080 54583"/>    <!--Гвард -->

        <npc id="42001" count="1" respawn="60" pos="145577 -70459 -4072 108"/>    <!--Гвард -->
        <npc id="42001" count="1" respawn="60" pos="145384 -70461 -4080 11247"/>    <!--Гвард -->
    </spawn>

</list>

=== dorocki228/test/gameserver/dist/data/spawn/spawnmaker/giant-cave.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../spawn.dtd">

<list>
  <territory name="gc1">
    <add x="183144" y="62840" zmin="-4242" zmax="-3742"/>
    <add x="183192" y="60392" zmin="-4242" zmax="-3742"/>
    <add x="184584" y="60392" zmin="-4242" zmax="-3742"/>
    <add x="184600" y="62760" zmin="-4242" zmax="-3742"/>
  </territory>
  <spawn group="giant_cave" name="gc1" territory="gc1">
    <!--Dryad-->
    <npc id="20656" count="2" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Scout-->
    <npc id="20654" count="2" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Soldier-->
    <!--Doom Knight-->
    <!--Trives-->
    <npc id="22674" count="2" respawn="60" respawn_random="0"/>
    <!--Imagro-->
    <npc id="22672" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Seer-->
    <npc id="22673" count="2" respawn="60" respawn_random="0"/>
    <!--Hirokai-->
  </spawn>
  <territory name="gc2">
    <add x="185384" y="61912" zmin="-4402" zmax="-3902"/>
    <add x="185448" y="60824" zmin="-4402" zmax="-3902"/>
    <add x="186568" y="60824" zmin="-4402" zmax="-3902"/>
    <add x="186568" y="61928" zmin="-4402" zmax="-3902"/>
  </territory>
  <spawn group="giant_cave" name="gc2" territory="gc2">
    <!--Dryad-->
    <npc id="22671" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Guardian-->
    <npc id="22676" count="2" respawn="60" respawn_random="0"/>
    <!--Hamlet-->
    <!--Lesser Giant Scout-->
    <npc id="20656" count="2" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Scout-->
  </spawn>
  <territory name="gc3">
    <add x="186488" y="60776" zmin="-4402" zmax="-3902"/>
    <add x="185480" y="60728" zmin="-4410" zmax="-3910"/>
    <add x="185496" y="59672" zmin="-4570" zmax="-4070"/>
    <add x="186504" y="59640" zmin="-4578" zmax="-4078"/>
  </territory>
  <spawn group="giant_cave" name="gc3" territory="gc3">
    <!--Dryad-->
    <npc id="22671" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Guardian-->
    <npc id="22672" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Seer-->
    <!--Hirokai-->
    <npc id="22673" count="2" respawn="60" respawn_random="0"/>
    <!--Hirokai-->
  </spawn>
  <territory name="gc4">
    <add x="186504" y="59592" zmin="-4578" zmax="-4078"/>
    <add x="185480" y="59560" zmin="-4586" zmax="-4086"/>
    <add x="185496" y="58008" zmin="-4818" zmax="-4318"/>
    <add x="186520" y="57976" zmin="-4818" zmax="-4318"/>
  </territory>
  <spawn group="giant_cave" name="gc4" territory="gc4">
    <!--Dryad-->
    <npc id="22674" count="2" respawn="60" respawn_random="0"/>
    <!--Imagro-->
    <npc id="22676" count="2" respawn="60" respawn_random="0"/>
    <!--Hamlet-->
    <!--Lesser Giant Soldier-->
    <npc id="20654" count="2" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Soldier-->
  </spawn>
  <territory name="gc5">
    <add x="186968" y="57848" zmin="-4818" zmax="-4318"/>
    <add x="185448" y="57848" zmin="-4818" zmax="-4318"/>
    <add x="185448" y="56280" zmin="-4818" zmax="-4318"/>
    <add x="186232" y="56248" zmin="-4818" zmax="-4318"/>
    <add x="186248" y="56968" zmin="-4818" zmax="-4318"/>
    <add x="186984" y="56984" zmin="-4818" zmax="-4318"/>
  </territory>
  <spawn group="giant_cave" name="gc5" territory="gc5">
    <!--Dryad-->
    <npc id="20656" count="2" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Scout-->
    <!--Kadios-->
    <npc id="22671" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Guardian-->
    <npc id="22672" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Seer-->
  </spawn>
  <territory name="gc6">
    <add x="186232" y="56216" zmin="-4818" zmax="-4318"/>
    <add x="185448" y="56184" zmin="-4818" zmax="-4318"/>
    <add x="185448" y="54648" zmin="-4818" zmax="-4318"/>
    <add x="187112" y="54680" zmin="-4818" zmax="-4318"/>
    <add x="187111" y="55543" zmin="-4818" zmax="-4318"/>
    <add x="186344" y="55544" zmin="-4818" zmax="-4318"/>
  </territory>
  <spawn group="giant_cave" name="gc6" territory="gc6">
    <!--Dryad-->
    <npc id="22673" count="2" respawn="60" respawn_random="0"/>
    <!--Hirokai-->
    <npc id="22674" count="2" respawn="60" respawn_random="0"/>
    <!--Imagro-->
    <npc id="22676" count="2" respawn="60" respawn_random="0"/>
    <!--Hamlet-->
  </spawn>
  <territory name="gc7">
    <add x="187144" y="55544" zmin="-4818" zmax="-4318"/>
    <add x="187207" y="54696" zmin="-4818" zmax="-4318"/>
    <add x="188312" y="54664" zmin="-4818" zmax="-4318"/>
    <add x="188312" y="56280" zmin="-4818" zmax="-4318"/>
    <add x="187576" y="56264" zmin="-4818" zmax="-4318"/>
    <add x="187560" y="55560" zmin="-4818" zmax="-4318"/>
  </territory>
  <spawn group="giant_cave" name="gc7" territory="gc7">
    <!--Dryad-->
    <npc id="20654" count="2" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Soldier-->
    <npc id="20656" count="2" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Scout-->
  </spawn>
  <territory name="gc8">
    <add x="187576" y="56296" zmin="-4818" zmax="-4318"/>
    <add x="188296" y="56360" zmin="-4818" zmax="-4318"/>
    <add x="188296" y="57848" zmin="-4818" zmax="-4318"/>
    <add x="187000" y="57848" zmin="-4818" zmax="-4318"/>
    <add x="187032" y="56984" zmin="-4818" zmax="-4318"/>
    <add x="187559" y="56968" zmin="-4818" zmax="-4318"/>
  </territory>
  <spawn group="giant_cave" name="gc8" territory="gc8">
    <!--Dryad-->
    <npc id="22671" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Guardian-->
    <npc id="22672" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Seer-->
  </spawn>
  <territory name="gc_rb">
    <add x="184392" y="61896" zmin="-4242" zmax="-3742"/>
    <add x="183544" y="62360" zmin="-4242" zmax="-3742"/>
    <add x="183559" y="61032" zmin="-4242" zmax="-3742"/>
    <add x="184408" y="60904" zmin="-4242" zmax="-3742"/>
  </territory>
  <spawn>
    <!--Refugee Applicant Leo-->
    <npc id="25122" count="1" respawn="82800" respawn_random="7200" pos="183559 61032 -3992 49152"/>
    <!--Refugee Applicant Leo-->
  </spawn>
  <territory name="gc9">
    <add x="181384" y="61176" zmin="-4242" zmax="-3742"/>
    <add x="182840" y="61144" zmin="-4242" zmax="-3742"/>
    <add x="182856" y="62760" zmin="-4242" zmax="-3742"/>
    <add x="181400" y="62760" zmin="-4242" zmax="-3742"/>
  </territory>
  <spawn name="gc9" territory="gc9">
    <npc id="20654" count="2" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Soldier-->
    <npc id="20656" count="2" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Scout-->
    <npc id="22671" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Guardian-->
    <npc id="22672" count="1" respawn="60" respawn_random="0"/>
    <!--Beastial Seer-->
  </spawn>
  <territory name="gc10">
    <add x="182584" y="60488" zmin="-4242" zmax="-3742"/>
    <add x="180808" y="60440" zmin="-4242" zmax="-3742"/>
    <add x="180808" y="58504" zmin="-4242" zmax="-3742"/>
    <add x="182584" y="58536" zmin="-4242" zmax="-3742"/>
  </territory>
  <spawn name="gc10" territory="gc10">
    <npc id="22673" count="2" respawn="60" respawn_random="0"/>
    <!--Hirokai-->
    <npc id="22674" count="2" respawn="60" respawn_random="0"/>
    <!--Imagro-->
    <npc id="22676" count="2" respawn="60" respawn_random="0"/>
    <!--Hamlet-->
    <npc id="20654" count="1" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Soldier-->
  </spawn>
  <territory name="gc11">
    <add x="184616" y="60120" zmin="-4242" zmax="-3742"/>
    <add x="183160" y="60104" zmin="-4242" zmax="-3742"/>
    <add x="183176" y="57720" zmin="-4242" zmax="-3742"/>
    <add x="184584" y="57736" zmin="-4242" zmax="-3742"/>
  </territory>
  <spawn name="gc11" territory="gc11">
    <npc id="20656" count="2" respawn="60" respawn_random="0"/>
    <!--Lesser Giant Scout-->
    <npc id="22671" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Guardian-->
    <npc id="22672" count="2" respawn="60" respawn_random="0"/>
    <!--Beastial Seer-->
    <npc id="22673" count="1" respawn="60" respawn_random="0"/>
    <!--Hirokai-->
    <npc id="22674" count="1" respawn="60" respawn_random="0"/>
    <!--Imagro-->
  </spawn>
</list>

=== dorocki228/test/gameserver/dist/data/spawn/talking_island.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>

	<!-- Talking Insland  -->
	<spawn group="ti_fire_post_1" name="ti_fire_post">
	
	<npc id="40031" count="1" respawn="600" pos="-106072 232296 -3648 0" />	<!--Пост огня -->
	
	<npc id="40035" count="1" respawn="60" pos="-105772 232296 -3648 0" />
	<npc id="40035" count="1" respawn="60" pos="-105812 232446 -3648 5458" /> 
	<npc id="40035" count="1" respawn="60" pos="-105922 232556 -3648 10917" /> 
	<npc id="40035" count="1" respawn="60" pos="-106072 232596 -3648 16375" /> 
	<npc id="40035" count="1" respawn="60" pos="-106222 232556 -3648 21833" /> 
	<npc id="40035" count="1" respawn="60" pos="-106332 232446 -3648 27292" /> 
	<npc id="40035" count="1" respawn="60" pos="-106372 232296 -3648 32750" /> 
	<npc id="40035" count="1" respawn="60" pos="-106332 232146 -3648 38208" /> 
	<npc id="40035" count="1" respawn="60" pos="-106222 232036 -3648 43667" /> 
	<npc id="40035" count="1" respawn="60" pos="-106072 231996 -3648 49125" /> 
	<npc id="40035" count="1" respawn="60" pos="-105922 232036 -3648 54583" /> 
	<npc id="40035" count="1" respawn="60" pos="-105812 232146 -3648 60042" />
	
	<npc id="40005" count="1" respawn="60" pos="-105944 232280 -3648 0" />	<!--Баффер -->
	<npc id="40032" count="1" respawn="60" pos="-106264 232248 -3656 0" />	<!--Капитан -->
		
	</spawn>

	<spawn group="ti_water_post_1" name="ti_water_post">
	
	<npc id="40038" count="1" respawn="600" pos="-105448 224472 -3648 0" />	<!--Пост воды -->
	
	<npc id="40042" count="1" respawn="60" pos="-105148 224472 -3648 0" />
	<npc id="40042" count="1" respawn="60" pos="-105188 224622 -3648 5458" />
	<npc id="40042" count="1" respawn="60" pos="-105298 224732 -3648 10917" /> 
	<npc id="40042" count="1" respawn="60" pos="-105448 224772 -3648 16375" /> 
	<npc id="40042" count="1" respawn="60" pos="-105598 224732 -3648 21833" /> 
	<npc id="40042" count="1" respawn="60" pos="-105708 224622 -3648 27292" /> 
	<npc id="40042" count="1" respawn="60" pos="-105748 224472 -3648 32750" /> 
	<npc id="40042" count="1" respawn="60" pos="-105708 224322 -3648 38208" /> 
	<npc id="40042" count="1" respawn="60" pos="-105598 224212 -3648 43667" /> 
	<npc id="40042" count="1" respawn="60" pos="-105448 224172 -3648 49125" /> 
	<npc id="40042" count="1" respawn="60" pos="-105298 224212 -3648 54583" /> 
	<npc id="40042" count="1" respawn="60" pos="-105188 224322 -3648 60042" />
	
	<npc id="40005" count="1" respawn="60" pos="-105592 224472 -3648 0" />	<!--Баффер -->
	<npc id="40039" count="1" respawn="60" pos="-105256 224504 -3640 0" />	<!--Капитан -->

	</spawn>

</list>

=== dorocki228/test/gameserver/dist/data/spawn/spawnmaker/outlaw-forest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../spawn.dtd">

<list>
  <territory name="of1">
    <add x="91720" y="-4136" zmin="-3642" zmax="-3142"/>
    <add x="92136" y="-6056" zmin="-3346" zmax="-2846"/>
    <add x="90312" y="-6408" zmin="-3306" zmax="-2806"/>
    <add x="89800" y="-3608" zmin="-3458" zmax="-2958"/>
  </territory>
  <spawn group="outlaw_forest" name="of1" territory="of1">
    <!--Dryad-->
    <!--Ol Mahum Transcender-->
    <npc id="20161" count="3" respawn="60" respawn_random="0"/>
    <!--Oel Mahum-->
    <npc id="21261" count="3" respawn="60" respawn_random="0"/>
    <!--Ol Mahum Transcender-->
  </spawn>
  <territory name="of2">
    <add x="89768" y="-3576" zmin="-3466" zmax="-2966"/>
    <add x="87160" y="-2969" zmin="-3642" zmax="-3142"/>
    <add x="87416" y="-5048" zmin="-3466" zmax="-2966"/>
    <add x="89064" y="-5336" zmin="-3338" zmax="-2838"/>
  </territory>
  <spawn group="outlaw_forest" name="of2" territory="of2">
    <!--Dryad-->
    <npc id="20574" count="2" respawn="60" respawn_random="0"/>
    <!--Elder Tarlk Basilisk-->
    <npc id="20575" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Warrior-->
    <!--Oel Mahum Shaman-->
    <npc id="20576" count="3" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Shaman-->
  </spawn>
  <territory name="of3">
    <add x="89064" y="-5368" zmin="-3338" zmax="-2838"/>
    <add x="89880" y="-5544" zmin="-3298" zmax="-2798"/>
    <add x="90743" y="-7416" zmin="-3258" zmax="-2758"/>
    <add x="90488" y="-9608" zmin="-3026" zmax="-2526"/>
    <add x="87544" y="-6856" zmin="-3402" zmax="-2902"/>
  </territory>
  <spawn group="outlaw_forest" name="of3" territory="of3">
    <!--Dryad-->
    <!--Ol Mahum Transcender-->
    <npc id="20574" count="2" respawn="60" respawn_random="0"/>
    <!--Elder Tarlk Basilisk-->
    <npc id="21263" count="2" respawn="60" respawn_random="0"/>
    <!--Ol Mahum Transcender-->
    <!--Oel Mahum Warrior-->
    <npc id="20576" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Shaman-->
    <npc id="21261" count="3" respawn="60" respawn_random="0"/>
    <!--Ol Mahum Transcender-->
    <npc id="20575" count="3" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Warrior-->
  </spawn>
  <territory name="of4">
    <add x="87400" y="-6808" zmin="-3402" zmax="-2902"/>
    <add x="88695" y="-5241" zmin="-3362" zmax="-2862"/>
    <add x="86024" y="-4856" zmin="-3514" zmax="-3014"/>
    <add x="84696" y="-7032" zmin="-3346" zmax="-2846"/>
  </territory>
  <spawn group="outlaw_forest" name="of4" territory="of4">
    <!--Dryad-->
    <!--Oel Mahum-->
    <npc id="20574" count="2" respawn="60" respawn_random="0"/>
    <!--Elder Tarlk Basilisk-->
    <npc id="20161" count="3" respawn="60" respawn_random="0"/>
    <!--Oel Mahum-->
    <npc id="20161" count="5" respawn="60" respawn_random="0"/>
    <!--Oel Mahum-->
  </spawn>
  <territory name="of5">
    <add x="84680" y="-7080" zmin="-3338" zmax="-2838"/>
    <add x="84520" y="-8024" zmin="-3162" zmax="-2662"/>
    <add x="86504" y="-8728" zmin="-3274" zmax="-2774"/>
    <add x="87128" y="-7288" zmin="-3250" zmax="-2750"/>
  </territory>
  <spawn group="outlaw_forest" name="of5" territory="of5">
    <!--Dryad-->
    <npc id="20575" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Warrior-->
    <!--Oel Mahum Shaman-->
    <npc id="20574" count="2" respawn="60" respawn_random="0"/>
    <!--Elder Tarlk Basilisk-->
    <npc id="20576" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Shaman-->
  </spawn>
  <territory name="of6">
    <add x="84520" y="-6888" zmin="-3354" zmax="-2854"/>
    <add x="82808" y="-5992" zmin="-3314" zmax="-2814"/>
    <add x="81608" y="-7064" zmin="-3138" zmax="-2638"/>
    <add x="81352" y="-8072" zmin="-3050" zmax="-2550"/>
    <add x="82808" y="-8200" zmin="-3074" zmax="-2574"/>
    <add x="84200" y="-8072" zmin="-3138" zmax="-2638"/>
  </territory>
  <spawn group="outlaw_forest" name="of6" territory="of6">
    <!--Dryad-->
    <npc id="20576" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Shaman-->
    <npc id="20575" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Warrior-->
    <npc id="20161" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum-->
    <!--Elder Tarlk Basilisk-->
    <npc id="21261" count="2" respawn="60" respawn_random="0"/>
    <!--Ol Mahum Transcender-->
    <npc id="20574" count="4" respawn="60" respawn_random="0"/>
    <!--Elder Tarlk Basilisk-->
  </spawn>
  <territory name="of7">
    <add x="84551" y="-6856" zmin="-3362" zmax="-2862"/>
    <add x="85976" y="-4824" zmin="-3522" zmax="-3022"/>
    <add x="87576" y="-4168" zmin="-3442" zmax="-2942"/>
    <add x="87032" y="-3000" zmin="-3626" zmax="-3126"/>
    <add x="85240" y="-3240" zmin="-3578" zmax="-3078"/>
    <add x="84664" y="-5064" zmin="-3482" zmax="-2982"/>
  </territory>
  <spawn group="outlaw_forest" name="of7" territory="of7">
    <!--Dryad-->
    <npc id="21261" count="2" respawn="60" respawn_random="0"/>
    <!--Ol Mahum Transcender-->
    <npc id="20574" count="2" respawn="60" respawn_random="0"/>
    <!--Elder Tarlk Basilisk-->
    <npc id="21263" count="2" respawn="60" respawn_random="0"/>
    <!--Ol Mahum Transcender-->
    <npc id="20161" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum-->
    <!--Oel Mahum Warrior-->
    <!--Oel Mahum Shaman-->
    <npc id="20575" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Warrior-->
    <npc id="20576" count="3" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Shaman-->
  </spawn>
  <territory name="of8">
    <add x="84376" y="-6728" zmin="-3362" zmax="-2862"/>
    <add x="84616" y="-5080" zmin="-3482" zmax="-2982"/>
    <add x="82152" y="-4568" zmin="-3410" zmax="-2910"/>
    <add x="81592" y="-5896" zmin="-3266" zmax="-2766"/>
  </territory>
  <territory name="of9">
    <add x="81992" y="-4872" zmin="-3410" zmax="-2910"/>
    <add x="80712" y="-2888" zmin="-3506" zmax="-3006"/>
    <add x="82968" y="-2600" zmin="-3738" zmax="-3238"/>
    <add x="83176" y="-4712" zmin="-3442" zmax="-2942"/>
  </territory>
  <spawn group="outlaw_forest" name="of8" territory="of8">
    <!--Dryad-->
    <!--Oel Mahum Shaman-->
    <!--Oel Mahum Warrior-->
    <npc id="20574" count="2" respawn="60" respawn_random="0"/>
    <!--Elder Tarlk Basilisk-->
    <npc id="21263" count="3" respawn="60" respawn_random="0"/>
    <!--Ol Mahum Transcender-->
    <npc id="20576" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Shaman-->
    <npc id="20575" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Warrior-->
  </spawn>
  <spawn group="outlaw_forest" name="of9" territory="of9">
    <!--Dryad-->
    <npc id="21261" count="2" respawn="60" respawn_random="0"/>
    <!--Ol Mahum Transcender-->
    <npc id="20576" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Shaman-->
    <!--Oel Mahum Warrior-->
    <npc id="20575" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Warrior-->
  </spawn>
  <territory name="of10">
    <add x="83224" y="-4744" zmin="-3442" zmax="-2942"/>
    <add x="84440" y="-4600" zmin="-3482" zmax="-2982"/>
    <add x="85112" y="-3080" zmin="-3634" zmax="-3134"/>
    <add x="85304" y="-2312" zmin="-3738" zmax="-3238"/>
    <add x="83048" y="-2312" zmin="-3786" zmax="-3286"/>
  </territory>
  <spawn group="outlaw_forest" name="of10" territory="of10">
    <!--Dryad-->
    <npc id="20574" count="2" respawn="60" respawn_random="0"/>
    <!--Elder Tarlk Basilisk-->
    <npc id="21263" count="2" respawn="60" respawn_random="0"/>
    <!--Ol Mahum Transcender-->
    <npc id="20575" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Warrior-->
  </spawn>
  <territory name="of11">
    <add x="82664" y="-2440" zmin="-3746" zmax="-3246"/>
    <add x="81032" y="-264" zmin="-3978" zmax="-3478"/>
    <add x="82216" y="648" zmin="-3898" zmax="-3398"/>
    <add x="86247" y="408" zmin="-3754" zmax="-3254"/>
    <add x="87064" y="-1624" zmin="-3770" zmax="-3270"/>
  </territory>
  <spawn group="outlaw_forest" name="of11" territory="of11">
    <!--Dryad-->
    <npc id="20576" count="2" respawn="60" respawn_random="0"/>
    <!--Oel Mahum Shaman-->
    <npc id="21261" count="2" respawn="60" respawn_random="0"/>
    <!--Ol Mahum Transcender-->
    <!--Oel Mahum-->
    <npc id="20161" count="3" respawn="60" respawn_random="0"/>
    <!--Oel Mahum-->
  </spawn>
  <territory name="of_rb">
    <add x="86184" y="-6312" zmin="-3442" zmax="-2942"/>
    <add x="86312" y="-5944" zmin="-3466" zmax="-2966"/>
    <add x="85992" y="-5896" zmin="-3482" zmax="-2982"/>
    <add x="85832" y="-6200" zmin="-3466" zmax="-2966"/>
  </territory>
  <spawn>
    <npc id="25060" count="1" respawn="82800" respawn_random="7200" pos="85992 -5896 -3240 49152"/>
    <!--Unrequited Kael-->
  </spawn>
</list>
