=== dorocki228/test/gameserver/dist/config/Phantom/items/weapons/weapon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list ((PhantomWeapons+))>
<!ELEMENT item EMPTY>
<!ATTLIST item
	item_id CDATA #REQUIRED
>
<!ELEMENT PhantomWeapons ((item))>
<!ATTLIST PhantomWeapons
	class_id CDATA #REQUIRED
	grade CDATA #REQUIRED
>

=== dorocki228/test/config/Phantom/items/weapons/2_3profa/Spellsinger.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "weapon.dtd">
<list>
	<PhantomWeapons class_id="27" grade="C">
		<item item_id="206" />  
	</PhantomWeapons>
	<PhantomWeapons class_id="27" grade="B">
		<item item_id="92" />  
	</PhantomWeapons>
	<PhantomWeapons class_id="27" grade="B">
		<item item_id="210" />  
	</PhantomWeapons>
	<PhantomWeapons class_id="27" grade="A">
		<item item_id="212" />  
	</PhantomWeapons>
	<PhantomWeapons class_id="27" grade="A">
		<item item_id="8688" />  
	</PhantomWeapons>
	<PhantomWeapons class_id="103" grade="S">
		<item item_id="6579" />   
	</PhantomWeapons>
 </list>
