=== dorocki228/test/data/items/item.dtd
<!ELEMENT list (weapon|etcitem|armor)*>
<!ELEMENT weapon  (set|equip|for|enchant4_skill|cond|skills|triggers|attributes|enchant_options|crystallization_info)*>
<!ATTLIST weapon
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT etcitem (set|equip|for|enchant4_skill|cond|skills|triggers|enchant_options|capsuled_items|crystallization_info)*>
<!ATTLIST etcitem
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT armor  (set|equip|for|enchant4_skill|cond|skills|triggers|attributes|enchant_options|crystallization_info)*>
<!ATTLIST armor
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>

<!ELEMENT enchant_options (level)*>
<!ELEMENT level (option)*>
<!ATTLIST level
	value CDATA #REQUIRED>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
	id CDATA #REQUIRED>

<!ELEMENT equip (slot|visual)*>
<!ELEMENT slot (#PCDATA)>
<!ATTLIST slot
	id CDATA #REQUIRED>
<!ELEMENT visual (change)*>
<!ELEMENT change (#PCDATA)>
<!ATTLIST change
		slot CDATA #REQUIRED
		to_id CDATA #REQUIRED>

<!ELEMENT cond (player|target|using|zone|or|not|and)*>
<!ATTLIST cond
	msgId CDATA #IMPLIED
	customMessageLink CDATA #IMPLIED>
<!ELEMENT or (player|target|using|zone|or|not|and)*>
<!ELEMENT not (player|target|using|zone|or|not|and)*>
<!ELEMENT and (player|target|using|zone|or|not|and)*>
<!ELEMENT player (#PCDATA)>
<!ATTLIST player
	fraction CDATA #IMPLIED
	percentHP CDATA #IMPLIED
	residence CDATA #IMPLIED
	olympiad CDATA #IMPLIED
	is_hero CDATA #IMPLIED
	race CDATA #IMPLIED
	instance_zone CDATA #IMPLIED
	is_clan_leader CDATA #IMPLIED
	sex CDATA #IMPLIED
	castle_type CDATA #IMPLIED
	classId CDATA #IMPLIED
	minLevel CDATA #IMPLIED
	max_level CDATA #IMPLIED
	avail_max_sp CDATA #IMPLIED
	quest_state CDATA #IMPLIED
	min_pledge_rank CDATA #IMPLIED
	class_type CDATA #IMPLIED
	min_clan_level CDATA #IMPLIED
	isFlagged CDATA #IMPLIED
	is_chaotic CDATA #IMPLIED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	is_pet_feed CDATA #IMPLIED
	type CDATA #IMPLIED>
<!ELEMENT using (#PCDATA)>
<!ATTLIST using
	slotitem CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	type CDATA #IMPLIED
	name CDATA #IMPLIED>

<!ELEMENT for (add|set|mul|enchant)*>
<!ELEMENT add (player|target|using|zone|or|not|and)*>
<!ATTLIST add
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT attributes (attribute)*>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute
	element CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT capsuled_items (capsuled_item)*>
<!ELEMENT capsuled_item (#PCDATA)>
<!ATTLIST capsuled_item
	id CDATA #REQUIRED
	min_count CDATA #REQUIRED
	max_count CDATA #REQUIRED
	chance CDATA #REQUIRED
	enchant_level CDATA #IMPLIED>

<!ELEMENT mul (player|target|using|zone)*>
<!ATTLIST mul
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT set (player|target|using|zone|or|not|and)*>
<!ATTLIST set
	name CDATA #IMPLIED
	order CDATA #IMPLIED
	stat CDATA #IMPLIED
	value CDATA #REQUIRED>

<!ELEMENT enchant (#PCDATA)>
<!ATTLIST enchant
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT enchant4_skill (#PCDATA)>
<!ATTLIST enchant4_skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED
	cancel_effects_on_remove CDATA #IMPLIED>

=== dorocki228/test/gameserver/src/dist/data/items/13800-13899.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="13894" name="Rag Belt" add_name="Not Available">
		<set name="price" value="45100"/>
		<set name="crystal_type" value="C"/>
		<set name="icon" value="icon.armor_belt_i00"/>
		<set name="type" value="LIGHT"/>
		<set name="weight" value="500"/>
		<equip>
			<slot id="BELT"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="10"/>
		</for>
	</armor>
	<armor id="13895" name="Leather Belt" add_name="Not Available">
		<set name="price" value="165000"/>
		<set name="crystal_type" value="B"/>
		<set name="icon" value="icon.armor_belt_i01"/>
		<set name="type" value="LIGHT"/>
		<set name="weight" value="480"/>
		<equip>
			<slot id="BELT"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="11"/>
		</for>
	</armor>
	<armor id="13896" name="Iron Belt" add_name="Not Available">
		<set name="price" value="371300"/>
		<set name="crystal_type" value="A"/>
		<set name="icon" value="icon.armor_belt_i02"/>
		<set name="type" value="LIGHT"/>
		<set name="weight" value="460"/>
		<equip>
			<slot id="BELT"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="12"/>
		</for>
	</armor>
	<armor id="13897" name="Mithril Belt" add_name="Not Available">
		<set name="price" value="1917000"/>
		<set name="crystal_type" value="S"/>
		<set name="icon" value="icon.armor_belt_i03"/>
		<set name="type" value="LIGHT"/>
		<set name="weight" value="440"/>
		<equip>
			<slot id="BELT"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="14"/>
		</for>
	</armor>
</list>

=== dorocki228/test/gameserver/dist/data/items/37500-37599.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="37533" name="NC Messenger\'s Hat">
		<set name="sellable" value="false" />
		<set name="privatestoreable" value="false" />
		<set name="dropable" value="false" />
		<set name="tradeable" value="false" />
		<set name="crystal_type" value="NONE" />
		<set name="icon" value="icon.nc_hair_acc" />
		<set name="price" value="0" />
		<set name="type" value="NONE" />
		<equip>
			<slot id="HAIR_ALL" />
		</equip>
	</armor>
	<armor id="37534" name="Santa Suit">
		<set name="sellable" value="false" />
		<set name="privatestoreable" value="false" />
		<set name="dropable" value="false" />
		<set name="tradeable" value="false" />
		<set name="crystal_type" value="NONE" />
		<set name="icon" value="icon.armor_ev_santas_clothes" />
		<set name="price" value="0" />
		<set name="type" value="HEAVY" />
		<equip>
			<slot id="FORMAL_WEAR" />
			<visual>
                <change slot="FORMAL_WEAR" to_id="37534"/>
			</visual>
		</equip>
	</armor>
	<armor id="37535" name="Santa Hat">
		<set name="sellable" value="false" />
		<set name="privatestoreable" value="false" />
		<set name="dropable" value="false" />
		<set name="tradeable" value="false" />
		<set name="crystal_type" value="NONE" />
		<set name="icon" value="icon.accessory_santas_cap_i00" />
		<set name="price" value="0" />
		<set name="type" value="NONE" />
		<equip>
			<slot id="HAIR_ALL" />
		</equip>
	</armor>
	<etcitem id="37543" name="Snowy Squash Nectar">
		<set name="sellable" value="false" />
		<set name="icon" value="icon.etc_nectar_i01" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
	<etcitem id="37544" name="Snowball">
		<set name="sellable" value="false" />
		<set name="icon" value="BranchSys2.icon.g_illumination_white" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
	<etcitem id="37545" name="Large Snowball">
		<set name="sellable" value="false" />
		<set name="icon" value="BranchSys2.icon.g_illumination_white" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
	<etcitem id="37546" name="Rudolf\'s Gift 2015" add_name="Lv. 1">
		<set name="icon" value="icon.etc_pi_gift_box_i04" />
		<set name="weight" value="10" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
	<etcitem id="37547" name="Rudolf\'s Gift 2015" add_name="Lv. 2">
		<set name="icon" value="icon.etc_pi_gift_box_i04" />
		<set name="weight" value="10" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
	<etcitem id="37548" name="Rudolf\'s Gift 2015" add_name="Lv. 3">
		<set name="icon" value="icon.etc_pi_gift_box_i04" />
		<set name="weight" value="10" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
	<etcitem id="37549" name="Rudolf\'s Gift 2015" add_name="Lv. 4">
		<set name="icon" value="icon.etc_pi_gift_box_i04" />
		<set name="weight" value="10" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
	<etcitem id="37550" name="Snowman\'s Buff">
		<set name="icon" value="icon.weapon_snowman_stick_i00" />
		<set name="weight" value="120" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
	<etcitem id="37551" name="Christmas Present">
		<set name="sellable" value="false" />
		<set name="icon" value="icon.etc_pi_gift_box_i04" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
	<etcitem id="37552" name="Snowy Squash Seed">
		<set name="icon" value="icon.etc_gourd_i10" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
	<etcitem id="37553" name="Large Snowy Squash Seed">
		<set name="icon" value="icon.etc_gourd_i11" />
		<set name="stackable" value="true" />
		<set name="crystal_type" value="NONE" />
	</etcitem>
</list>

=== dorocki228/test/gameserver/dist/data/items/06500-06599.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<etcitem id="6571" name="Blessed Scroll: Enchant Weapon (B-grade)" add_name="Not in Use">
		<set name="type" value="SCROLL_ENCHANT_WEAPON"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_wp_b_i03"/>
		<set name="price" value="7000000"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="120"/>
	</etcitem>
	<etcitem id="6572" name="Blessed Scroll: Enchant Armor (B-grade)" add_name="Not in Use">
		<set name="type" value="SCROLL_ENCHANT_ARMOR"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_am_b_i03"/>
		<set name="price" value="750000"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="120"/>
	</etcitem>
	<etcitem id="6573" name="Blessed Scroll: Enchant Weapon (C-grade)" add_name="Not in Use">
		<set name="type" value="SCROLL_ENCHANT_WEAPON"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_wp_c_i02"/>
		<set name="price" value="3000000"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="120"/>
	</etcitem>
	<etcitem id="6574" name="Blessed Scroll: Enchant Armor (C-grade)" add_name="Not in Use">
		<set name="type" value="SCROLL_ENCHANT_ARMOR"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_am_c_i02"/>
		<set name="price" value="350000"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="120"/>
	</etcitem>
	<etcitem id="6575" name="Blessed Scroll: Enchant Weapon (D-grade)" add_name="Not in Use">
		<set name="type" value="SCROLL_ENCHANT_WEAPON"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_wp_d_i01"/>
		<set name="price" value="900000"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="120"/>
	</etcitem>
	<etcitem id="6576" name="Blessed Scroll: Enchant Armor (D-grade)" add_name="Not in Use">
		<set name="type" value="SCROLL_ENCHANT_ARMOR"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_am_d_i01"/>
		<set name="price" value="100000"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="120"/>
	</etcitem>
</list>

=== dorocki228/test/gameserver/src/dist/data/items/91700-91799.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="91700" name="Karmian Tunic">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.armor_t53_u_i00"/>
		<set name="type" value="MAGIC"/>
		<set name="weight" value="1980"/>
		<equip>
			<slot id="CHEST"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="60"/>
			<add stat="maxMp" order="0x60" value="225"/>
		</for>
	</armor>
	<armor id="91701" name="Karmian Stockings">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.armor_t53_l_i00"/>
		<set name="type" value="MAGIC"/>
		<set name="weight" value="970"/>
		<equip>
			<slot id="LEGS"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="37"/>
			<add stat="maxMp" order="0x60" value="141"/>
		</for>
	</armor>
	<armor id="91702" name="Karmian Boots">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.armor_t53_b_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="1230"/>
		<equip>
			<slot id="FEET"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="32"/>
		</for>
	</armor>
	<armor id="91703" name="Karmian Gloves">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.armor_t53_g_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="620"/>
		<equip>
			<slot id="GLOVES"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="32"/>
		</for>
	</armor>
	<armor id="91704" name="Plated Leather Armor">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.armor_t47_u_i00"/>
		<set name="type" value="LIGHT"/>
		<set name="weight" value="4450"/>
		<equip>
			<slot id="CHEST"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="94"/>
		</for>
	</armor>
	<armor id="91705" name="Plated Leather Gaiters">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.armor_t47_l_i00"/>
		<set name="type" value="LIGHT"/>
		<set name="weight" value="1560"/>
		<equip>
			<slot id="LEGS"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="59"/>
		</for>
	</armor>
	<armor id="91706" name="Plated Leather Boots">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.armor_t47_b_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="1220"/>
		<equip>
			<slot id="FEET"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="32"/>
		</for>
	</armor>
	<armor id="91707" name="Plated Leather Gloves">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.armor_t47_g_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="610"/>
		<equip>
			<slot id="GLOVES"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="33"/>
		</for>
	</armor>
	<armor id="91719" name="Sayha's Supreme Cloak - Black">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="BranchIcon.icon.g_bm_elmoreden_cloak_normal"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="220"/>
		<equip>
			<slot id="BACK"/>
		</equip>
		<for>
			<mul stat="maxHp" order="0x10" value="1.05"/>
			<mul stat="maxMp" order="0x10" value="1.05"/>
			<mul stat="maxCp" order="0x10" value="1.05"/>
			<mul stat="pDef" order="0x10" value="1.05"/>
			<mul stat="mDef" order="0x10" value="1.05"/>
		</for>
	</armor>
	<armor id="91720" name="Sayha's Supreme Cloak - White">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="BranchIcon.icon.g_bm_elmoreden_cloak_normal"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="220"/>
		<equip>
			<slot id="BACK"/>
		</equip>
		<for>
			<mul stat="maxHp" order="0x10" value="1.05"/>
			<mul stat="maxMp" order="0x10" value="1.05"/>
			<mul stat="maxCp" order="0x10" value="1.05"/>
			<mul stat="pDef" order="0x10" value="1.05"/>
			<mul stat="mDef" order="0x10" value="1.05"/>
		</for>
	</armor>
	<armor id="91721" name="Sayha's Supreme Cloak - Red">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="BranchIcon.icon.g_bm_elmoreden_cloak_normal"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="220"/>
		<equip>
			<slot id="BACK"/>
		</equip>
		<for>
			<mul stat="maxHp" order="0x10" value="1.05"/>
			<mul stat="maxMp" order="0x10" value="1.05"/>
			<mul stat="maxCp" order="0x10" value="1.05"/>
			<mul stat="pDef" order="0x10" value="1.05"/>
			<mul stat="mDef" order="0x10" value="1.05"/>
		</for>
	</armor>
</list>
