=== dorocki228/test/gameserver/src/dist/data/skill_tree/tree.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (general_skill_tree|certification_skill_tree|sub_unit_skill_tree|pledge_skill_tree|normal_skill_tree|fishing_skill_tree|hero_skill_tree|gm_skill_tree|custom_skill_tree)*>
<!ELEMENT general_skill_tree (skill|class)*>
<!ELEMENT normal_skill_tree (class)*>
<!ELEMENT certification_skill_tree (skill)*>
<!ELEMENT sub_unit_skill_tree (skill)*>
<!ELEMENT pledge_skill_tree (skill)*>
<!ELEMENT fishing_skill_tree (skill)*>
<!ELEMENT hero_skill_tree (skill)*>
<!ELEMENT gm_skill_tree (skill)*>
<!ELEMENT custom_skill_tree (skill)*>
	<!ELEMENT skill (player|or|not|and)*>
		<!ATTLIST skill
			id CDATA #REQUIRED
			item_count CDATA #IMPLIED
			item_id CDATA #IMPLIED
			level CDATA #REQUIRED
			min_level CDATA #IMPLIED
			name CDATA #IMPLIED
			cost CDATA #IMPLIED
			race CDATA #IMPLIED
			auto_get CDATA #IMPLIED>

			<!ELEMENT or (player|or|not|and)*>
			<!ELEMENT not (player|or|not|and)*>
			<!ELEMENT and (player|or|not|and)*>
			<!ELEMENT player (#PCDATA)>
			<!ATTLIST player
				residence CDATA #IMPLIED
				race CDATA #IMPLIED
				is_clan_leader CDATA #IMPLIED
				sex CDATA #IMPLIED
				castle_type CDATA #IMPLIED
				classId CDATA #IMPLIED
				minLevel CDATA #IMPLIED
				max_level CDATA #IMPLIED
				avail_max_sp CDATA #IMPLIED
				quest_state CDATA #IMPLIED
				min_pledge_rank CDATA #IMPLIED
				class_type CDATA #IMPLIED
				min_clan_level CDATA #IMPLIED
				isFlagged CDATA #IMPLIED>

	<!ELEMENT class (skill)*>
		<!ATTLIST class
			id CDATA #IMPLIED
			level CDATA #IMPLIED>

=== dorocki228/test/gameserver/src/dist/data/skill_tree/normal_skill_tree/[109] ghost_sentinel.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--AUTHOR: Bonux-->
<list>
	<normal_skill_tree>
		<class id="109">	<!--Страж Теней-->
			<skill id="1405" level="3" name="Божественное Вдохновение(Divine Inspiration)" item_id="8620" cost="6300000" min_level="76"/>
			<skill id="1405" level="4" name="Божественное Вдохновение(Divine Inspiration)" item_id="8621" cost="6300000" min_level="76"/>
			<skill id="233" level="48" name="Владение Легкой Броней(Light Armor Mastery)" cost="6300000" min_level="76"/>
			<skill id="208" level="53" name="Владение Луком(Bow Mastery)" cost="6300000" min_level="76"/>
			<skill id="19" level="38" name="Двойной Выстрел(Double Shot)" cost="6300000" min_level="76"/>
			<skill id="415" level="1" name="Дух Стрельца(Spirit of Sagittarius)" cost="6300000" min_level="76"/>
			<skill id="223" level="50" name="Жало(Sting)" cost="6300000" min_level="76"/>
			<skill id="105" level="25" name="Замораживающий Удар(Freezing Strike)" cost="6300000" min_level="76"/>
			<skill id="70" level="54" name="Кража Здоровья(Drain HP)" cost="6300000" min_level="76"/>
			<skill id="53005" level="1" name="Найти Тьму()" cost="6300000" min_level="76"/>
			<skill id="314" level="17" name="Обратный Отсчет(Fatal Counter)" cost="6300000" min_level="76"/>
			<skill id="101" level="41" name="Оглушающий Выстрел(Stun Shot)" cost="6300000" min_level="76"/>
			<skill id="1835" level="1" name="Оседлать Саблезубого Кугуара(Mount Saber Tooth Cougar)" item_id="90040" min_level="76"/>
			<skill id="122" level="16" name="Сглаз(Hex)" cost="6300000" min_level="76"/>
			<skill id="343" level="1" name="Смертельный Выстрел(Lethal Shot)" cost="6300000" min_level="76"/>
			<skill id="115" level="18" name="Сокрушение Мощи(Power Break)" cost="6300000" min_level="76"/>
			<skill id="233" level="49" name="Владение Легкой Броней(Light Armor Mastery)" cost="6300000" min_level="77"/>
			<skill id="208" level="54" name="Владение Луком(Bow Mastery)" cost="6300000" min_level="77"/>
			<skill id="19" level="39" name="Двойной Выстрел(Double Shot)" cost="6300000" min_level="77"/>
			<skill id="223" level="51" name="Жало(Sting)" cost="6300000" min_level="77"/>
			<skill id="354" level="1" name="Калечащий Выстрел(Hamstring Shot)" cost="6300000" min_level="77"/>
			<skill id="70" level="55" name="Кража Здоровья(Drain HP)" cost="6300000" min_level="77"/>
			<skill id="314" level="18" name="Обратный Отсчет(Fatal Counter)" cost="6300000" min_level="77"/>
			<skill id="101" level="42" name="Оглушающий Выстрел(Stun Shot)" cost="6300000" min_level="77"/>
			<skill id="343" level="2" name="Смертельный Выстрел(Lethal Shot)" cost="6300000" min_level="77"/>
			<skill id="233" level="50" name="Владение Легкой Броней(Light Armor Mastery)" cost="14700000" min_level="78"/>
			<skill id="208" level="55" name="Владение Луком(Bow Mastery)" cost="14700000" min_level="78"/>
			<skill id="522" level="1" name="Главная Цель(Real Target)" item_id="90062" cost="14700000" min_level="78"/>
			<skill id="19" level="40" name="Двойной Выстрел(Double Shot)" cost="14700000" min_level="78"/>
			<skill id="223" level="52" name="Жало(Sting)" cost="14700000" min_level="78"/>
			<skill id="105" level="26" name="Замораживающий Удар(Freezing Strike)" cost="14700000" min_level="78"/>
			<skill id="70" level="56" name="Кража Здоровья(Drain HP)" cost="14700000" min_level="78"/>
			<skill id="314" level="19" name="Обратный Отсчет(Fatal Counter)" cost="14700000" min_level="78"/>
			<skill id="101" level="43" name="Оглушающий Выстрел(Stun Shot)" cost="14700000" min_level="78"/>
			<skill id="122" level="17" name="Сглаз(Hex)" cost="14700000" min_level="78"/>
			<skill id="343" level="3" name="Смертельный Выстрел(Lethal Shot)" cost="14700000" min_level="78"/>
			<skill id="115" level="19" name="Сокрушение Мощи(Power Break)" cost="14700000" min_level="78"/>
			<skill id="343" level="4" name="Смертельный Выстрел(Lethal Shot)" cost="14700000" min_level="79"/>
			<skill id="990" level="1" name="Укол Смерти(Death Sting)" item_id="90063" cost="14700000" min_level="79"/>
			<skill id="233" level="51" name="Владение Легкой Броней(Light Armor Mastery)" cost="14700000" min_level="80"/>
			<skill id="208" level="56" name="Владение Луком(Bow Mastery)" cost="14700000" min_level="80"/>
			<skill id="522" level="2" name="Главная Цель(Real Target)" cost="14700000" min_level="80"/>
			<skill id="19" level="41" name="Двойной Выстрел(Double Shot)" cost="14700000" min_level="80"/>
			<skill id="414" level="9" name="Мертвый Глаз(Dead Eye)" cost="14700000" min_level="80"/>
			<skill id="101" level="44" name="Оглушающий Выстрел(Stun Shot)" cost="14700000" min_level="80"/>
			<skill id="773" level="1" name="Призрачное Пробивание(Ghost Piercing)" item_id="90066" cost="14700000" min_level="80"/>
			<skill id="343" level="5" name="Смертельный Выстрел(Lethal Shot)" cost="14700000" min_level="80"/>
			<skill id="233" level="52" name="Владение Легкой Броней(Light Armor Mastery)" cost="160000000" min_level="81"/>
			<skill id="208" level="57" name="Владение Луком(Bow Mastery)" cost="160000000" min_level="81"/>
			<skill id="19" level="42" name="Двойной Выстрел(Double Shot)" cost="160000000" min_level="81"/>
			<skill id="101" level="45" name="Оглушающий Выстрел(Stun Shot)" cost="160000000" min_level="81"/>
			<skill id="343" level="6" name="Смертельный Выстрел(Lethal Shot)" cost="160000000" min_level="81"/>
			<skill id="233" level="53" name="Владение Легкой Броней(Light Armor Mastery)" cost="170000000" min_level="82"/>
			<skill id="208" level="58" name="Владение Луком(Bow Mastery)" cost="170000000" min_level="82"/>
			<skill id="522" level="3" name="Главная Цель(Real Target)" cost="170000000" min_level="82"/>
			<skill id="19" level="43" name="Двойной Выстрел(Double Shot)" cost="170000000" min_level="82"/>
			<skill id="101" level="46" name="Оглушающий Выстрел(Stun Shot)" cost="170000000" min_level="82"/>
			<skill id="343" level="7" name="Смертельный Выстрел(Lethal Shot)" cost="170000000" min_level="82"/>
			<skill id="233" level="54" name="Владение Легкой Броней(Light Armor Mastery)" cost="240000000" min_level="83"/>
			<skill id="208" level="59" name="Владение Луком(Bow Mastery)" cost="240000000" min_level="83"/>
			<skill id="19" level="44" name="Двойной Выстрел(Double Shot)" cost="240000000" min_level="83"/>
			<skill id="101" level="47" name="Оглушающий Выстрел(Stun Shot)" cost="240000000" min_level="83"/>
			<skill id="343" level="8" name="Смертельный Выстрел(Lethal Shot)" cost="240000000" min_level="83"/>
			<skill id="233" level="55" name="Владение Легкой Броней(Light Armor Mastery)" cost="240000000" min_level="84"/>
			<skill id="208" level="60" name="Владение Луком(Bow Mastery)" cost="240000000" min_level="84"/>
			<skill id="522" level="4" name="Главная Цель(Real Target)" cost="240000000" min_level="84"/>
			<skill id="19" level="45" name="Двойной Выстрел(Double Shot)" cost="240000000" min_level="84"/>
			<skill id="101" level="48" name="Оглушающий Выстрел(Stun Shot)" cost="240000000" min_level="84"/>
			<skill id="343" level="9" name="Смертельный Выстрел(Lethal Shot)" cost="240000000" min_level="84"/>
			<skill id="233" level="56" name="Владение Легкой Броней()" cost="840000000" min_level="85"/>
			<skill id="208" level="61" name="Владение Луком()" cost="840000000" min_level="85"/>
		</class>
	</normal_skill_tree>
</list>

=== dorocki228/test/data/skill_tree/normal_skill_tree/[100] sword_muse.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "../tree.dtd">
<list>
	<normal_skill_tree>
		<class id="100"> <!--Виртуоз-->
			<skill id="1322" level="1" name="Common Craft" cost="0" min_level="1"/>
			<skill id="1320" level="10" name="Common Craft Passive" cost="0" min_level="1"/>
			<skill id="246" level="1" name="Печать" cost="0" min_level="1"/>
			<skill id="6088" level="1" name="Блок Бафф" cost="0" min_level="1"/>
			<skill id="402" level="11" name="Арест(Arrest)" cost="10200000" min_level="76"/>
			<skill id="1405" level="3" name="Божественное Вдохновение(Divine Inspiration)" cost="10200000" min_level="76"/>
			<skill id="1405" level="4" name="Божественное Вдохновение(Divine Inspiration)" cost="10200000" min_level="76"/>
			<skill id="217" level="46" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="10200000" min_level="76"/>
			<skill id="147" level="52" name="Магическое Сопротивление(M. Def.)" cost="10200000" min_level="76"/>
			<skill id="102" level="17" name="Опутать(Entangle)" cost="10200000" min_level="76"/>
			<skill id="1834" level="1" name="Оседлать Пегаса(Mount Pegasus)" cost="0" min_level="76"/>
			<skill id="15" level="53" name="Очарование(Charm)" cost="10200000" min_level="76"/>
			<skill id="98" level="6" name="Симфония Меча(Sword Symphony)" cost="10200000" min_level="76"/>
<!--			<skill id="986" level="16" name="Смертельный Ритм(Deadly Strike)" cost="10200000" min_level="76"/>-->
			<skill id="217" level="47" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="10200000" min_level="77"/>
			<skill id="147" level="53" name="Магическое Сопротивление(M. Def.)" cost="10200000" min_level="77"/>
			<skill id="349" level="1" name="Песня Возрождения(Song of Renewal)" cost="10200000" min_level="77"/>
			<!--			<skill id="986" level="17" name="Смертельный Ритм(Deadly Strike)" cost="10200000" min_level="77"/>-->
			<skill id="402" level="12" name="Арест(Arrest)" cost="23800000" min_level="78"/>
			<skill id="217" level="48" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="23800000" min_level="78"/>
			<skill id="147" level="54" name="Магическое Сопротивление(M. Def.)" cost="23800000" min_level="78"/>
			<skill id="102" level="18" name="Опутать(Entangle)" cost="23800000" min_level="78"/>
			<skill id="15" level="54" name="Очарование(Charm)" cost="23800000" min_level="78"/>
			<skill id="364" level="1" name="Песня Чемпиона(Champion Song)" cost="23800000" min_level="78"/>
			<!--			<skill id="986" level="18" name="Смертельный Ритм(Deadly Strike)" cost="23800000" min_level="78"/>-->
			<skill id="437" level="1" name="Песня Тишины(Song of Silence)" cost="23800000" min_level="79"/>
			<skill id="914" level="1" name="Песня Очищения(Song of Purification)" cost="23800000" min_level="80"/>
		</class>
	</normal_skill_tree>
</list>
