=== dorocki228/test/gameserver/src/dist/data/skill_tree/tree.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (general_skill_tree|certification_skill_tree|sub_unit_skill_tree|pledge_skill_tree|normal_skill_tree|fishing_skill_tree|hero_skill_tree|gm_skill_tree|custom_skill_tree)*>
<!ELEMENT general_skill_tree (skill|class)*>
<!ELEMENT normal_skill_tree (class)*>
<!ELEMENT certification_skill_tree (skill)*>
<!ELEMENT sub_unit_skill_tree (skill)*>
<!ELEMENT pledge_skill_tree (skill)*>
<!ELEMENT fishing_skill_tree (skill)*>
<!ELEMENT hero_skill_tree (skill)*>
<!ELEMENT gm_skill_tree (skill)*>
<!ELEMENT custom_skill_tree (skill)*>
	<!ELEMENT skill (player|or|not|and)*>
		<!ATTLIST skill
			id CDATA #REQUIRED
			item_count CDATA #IMPLIED
			item_id CDATA #IMPLIED
			level CDATA #REQUIRED
			min_level CDATA #IMPLIED
			name CDATA #IMPLIED
			cost CDATA #IMPLIED
			race CDATA #IMPLIED
			auto_get CDATA #IMPLIED>

			<!ELEMENT or (player|or|not|and)*>
			<!ELEMENT not (player|or|not|and)*>
			<!ELEMENT and (player|or|not|and)*>
			<!ELEMENT player (#PCDATA)>
			<!ATTLIST player
				residence CDATA #IMPLIED
				race CDATA #IMPLIED
				is_clan_leader CDATA #IMPLIED
				sex CDATA #IMPLIED
				castle_type CDATA #IMPLIED
				classId CDATA #IMPLIED
				minLevel CDATA #IMPLIED
				max_level CDATA #IMPLIED
				avail_max_sp CDATA #IMPLIED
				quest_state CDATA #IMPLIED
				min_pledge_rank CDATA #IMPLIED
				class_type CDATA #IMPLIED
				min_clan_level CDATA #IMPLIED
				isFlagged CDATA #IMPLIED>

	<!ELEMENT class (skill)*>
		<!ATTLIST class
			id CDATA #IMPLIED
			level CDATA #IMPLIED>

=== dorocki228/test/gameserver/dist/data/skill_tree/normal_skill_tree/[108] ghost_hunter.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "../tree.dtd">
<list>
	<normal_skill_tree>
		<class id="108"> <!--Призрачный Охотник-->
			<skill id="1322" level="1" name="Common Craft" cost="0" min_level="1"/>
			<skill id="1320" level="10" name="Common Craft Passive" cost="0" min_level="1"/>
			<skill id="246" level="1" name="Печать" cost="0" min_level="1"/>
			<skill id="6088" level="1" name="Блок Бафф" cost="0" min_level="1"/>
			<skill id="1405" level="3" name="Божественное Вдохновение(Divine Inspiration)" cost="5900000" min_level="76"/>
			<skill id="1405" level="4" name="Божественное Вдохновение(Divine Inspiration)" cost="5900000" min_level="76"/>
			<skill id="1630" level="1" name="Бросок Кровавого Кинжала(Throwing Blood Dagger)" cost="5900000" min_level="76"/>
			<skill id="209" level="46" name="Владение Кинжалом(Dagger Mastery)" cost="5900000" min_level="76"/>
			<skill id="233" level="48" name="Владение Легкой Броней(Light Armor Mastery)" cost="5900000" min_level="76"/>
			<skill id="223" level="50" name="Жало(Sting)" cost="5900000" min_level="76"/>
			<skill id="105" level="25" name="Замораживающий Удар(Freezing Strike)" cost="5900000" min_level="76"/>
			<skill id="70" level="54" name="Кража Здоровья(Drain HP)" cost="5900000" min_level="76"/>
			<skill id="96" level="7" name="Кровопускание(Bleed)" cost="5900000" min_level="76"/>
			<skill id="1835" level="1" name="Оседлать Саблезубого Кугуара(Mount Saber Tooth Cougar)" cost="0" min_level="76"/>
			<skill id="122" level="16" name="Сглаз(Hex)" cost="5900000" min_level="76"/>
			<skill id="263" level="38" name="Смертельный Импульс(Deadly Blow)" cost="5900000" min_level="76"/>
			<skill id="344" level="1" name="Смертоносный Удар(Lethal Blow)" cost="5900000" min_level="76"/>
			<skill id="115" level="18" name="Сокрушение Мощи(Power Break)" cost="5900000" min_level="76"/>
			<skill id="30" level="38" name="Удар в Спину(Backstab)" cost="5900000" min_level="76"/>
			<skill id="209" level="47" name="Владение Кинжалом(Dagger Mastery)" cost="5900000" min_level="77"/>
			<skill id="233" level="49" name="Владение Легкой Броней(Light Armor Mastery)" cost="5900000" min_level="77"/>
			<skill id="223" level="51" name="Жало(Sting)" cost="5900000" min_level="77"/>
			<skill id="70" level="55" name="Кража Здоровья(Drain HP)" cost="5900000" min_level="77"/>
			<skill id="531" level="1" name="Критическая Рана(Critical Wound)" cost="5900000" min_level="77"/>
			<skill id="1631" level="1" name="Сброс Движений(Clear Movements)" cost="5900000" min_level="77"/>
			<skill id="263" level="39" name="Смертельный Импульс(Deadly Blow)" cost="5900000" min_level="77"/>
			<skill id="30" level="39" name="Удар в Спину(Backstab)" cost="5900000" min_level="77"/>
			<skill id="209" level="48" name="Владение Кинжалом(Dagger Mastery)" cost="14000000" min_level="78"/>
			<skill id="233" level="50" name="Владение Легкой Броней(Light Armor Mastery)" cost="14000000" min_level="78"/>
			<skill id="223" level="52" name="Жало(Sting)" cost="14000000" min_level="78"/>
			<skill id="105" level="26" name="Замораживающий Удар(Freezing Strike)" cost="14000000" min_level="78"/>
			<skill id="70" level="56" name="Кража Здоровья(Drain HP)" cost="14000000" min_level="78"/>
			<skill id="412" level="11" name="Песочная Бомба(Sand Bomb)" cost="14000000" min_level="78"/>
			<skill id="122" level="17" name="Сглаз(Hex)" cost="14000000" min_level="78"/>
			<skill id="263" level="40" name="Смертельный Импульс(Deadly Blow)" cost="14000000" min_level="78"/>
			<skill id="115" level="19" name="Сокрушение Мощи(Power Break)" cost="14000000" min_level="78"/>
			<skill id="30" level="40" name="Удар в Спину(Backstab)" cost="14000000" min_level="78"/>
			<skill id="357" level="1" name="Фокусировка Мощности(Focus Power)" cost="14000000" min_level="78"/>
			<skill id="355" level="1" name="Фокусировка Смерти(Focus Death)" cost="14000000" min_level="78"/>
			<skill id="447" level="1" name="Контратака(Counterattack)" cost="14000000" min_level="79"/>
			<skill id="770" level="1" name="Походка Призрака(Ghost Walking)" cost="14000000" min_level="80"/>
		</class>
	</normal_skill_tree>
</list>

=== dorocki228/test/gameserver/src/dist/data/skill_tree/normal_skill_tree/[4] knight.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--AUTHOR: Bonux-->
<list>
	<normal_skill_tree>
		<class id="4">	<!--Рыцарь-->
			<skill id="110" level="1" name="Абсолютная Защита(Ultimate Defense)" cost="1000" min_level="20"/>
			<skill id="82" level="1" name="Величие(Majesty)" cost="1000" min_level="20"/>
			<skill id="217" level="1" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="1000" min_level="20"/>
			<skill id="232" level="1" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="1000" min_level="20"/>
			<skill id="232" level="2" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="1000" min_level="20"/>
			<skill id="232" level="3" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="1000" min_level="20"/>
			<skill id="153" level="1" name="Владение Щитом(Shield Mastery)" cost="1000" min_level="20"/>
			<skill id="70" level="1" name="Кража Здоровья(Drain HP)" cost="1000" min_level="20"/>
			<skill id="147" level="1" name="Магическое Сопротивление(Magic Resistance)" cost="1000" min_level="20"/>
			<skill id="147" level="2" name="Магическое Сопротивление(Magic Resistance)" cost="1000" min_level="20"/>
			<skill id="92" level="1" name="Оглушение Щитом(Shield Stun)" cost="1000" min_level="20"/>
			<skill id="92" level="2" name="Оглушение Щитом(Shield Stun)" cost="1000" min_level="20"/>
			<skill id="92" level="3" name="Оглушение Щитом(Shield Stun)" cost="1000" min_level="20"/>
			<skill id="28" level="1" name="Агрессия(Aggression)" cost="2800" min_level="22"/>
			<skill id="232" level="4" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="2800" min_level="22"/>
			<skill id="70" level="2" name="Кража Здоровья(Drain HP)" cost="2800" min_level="22"/>
			<skill id="147" level="3" name="Магическое Сопротивление(Magic Resistance)" cost="2800" min_level="22"/>
			<skill id="92" level="4" name="Оглушение Щитом(Shield Stun)" cost="2800" min_level="22"/>
			<skill id="28" level="2" name="Агрессия(Aggression)" cost="2800" min_level="23"/>
			<skill id="232" level="5" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="2800" min_level="23"/>
			<skill id="70" level="3" name="Кража Здоровья(Drain HP)" cost="2800" min_level="23"/>
			<skill id="147" level="4" name="Магическое Сопротивление(Magic Resistance)" cost="2800" min_level="23"/>
			<skill id="92" level="5" name="Оглушение Щитом(Shield Stun)" cost="2800" min_level="23"/>
			<skill id="28" level="3" name="Агрессия(Aggression)" cost="2800" min_level="24"/>
			<skill id="217" level="2" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="2800" min_level="24"/>
			<skill id="232" level="6" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="2800" min_level="24"/>
			<skill id="70" level="4" name="Кража Здоровья(Drain HP)" cost="2800" min_level="24"/>
			<skill id="147" level="5" name="Магическое Сопротивление(Magic Resistance)" cost="2800" min_level="24"/>
			<skill id="92" level="6" name="Оглушение Щитом(Shield Stun)" cost="2800" min_level="24"/>
			<skill id="112" level="1" name="Отклонить Стрелу(Deflect Arrow)" cost="2800" min_level="24"/>
			<skill id="28" level="4" name="Агрессия(Aggression)" cost="5700" min_level="26"/>
			<skill id="217" level="3" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="5700" min_level="26"/>
			<skill id="232" level="7" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="5700" min_level="26"/>
			<skill id="70" level="5" name="Кража Здоровья(Drain HP)" cost="5700" min_level="26"/>
			<skill id="147" level="6" name="Магическое Сопротивление(Magic Resistance)" cost="5700" min_level="26"/>
			<skill id="92" level="7" name="Оглушение Щитом(Shield Stun)" cost="5700" min_level="26"/>
			<skill id="45" level="1" name="Святое Лечение(Divine Heal)" cost="5700" min_level="26"/>
			<skill id="28" level="5" name="Агрессия(Aggression)" cost="5700" min_level="27"/>
			<skill id="232" level="8" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="5700" min_level="27"/>
			<skill id="70" level="6" name="Кража Здоровья(Drain HP)" cost="5700" min_level="27"/>
			<skill id="147" level="7" name="Магическое Сопротивление(Magic Resistance)" cost="5700" min_level="27"/>
			<skill id="92" level="8" name="Оглушение Щитом(Shield Stun)" cost="5700" min_level="27"/>
			<skill id="45" level="2" name="Святое Лечение(Divine Heal)" cost="5700" min_level="27"/>
			<skill id="28" level="6" name="Агрессия(Aggression)" cost="5700" min_level="28"/>
			<skill id="217" level="4" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="5700" min_level="28"/>
			<skill id="232" level="9" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="5700" min_level="28"/>
			<skill id="153" level="2" name="Владение Щитом(Shield Mastery)" cost="5700" min_level="28"/>
			<skill id="70" level="7" name="Кража Здоровья(Drain HP)" cost="5700" min_level="28"/>
			<skill id="147" level="8" name="Магическое Сопротивление(Magic Resistance)" cost="5700" min_level="28"/>
			<skill id="92" level="9" name="Оглушение Щитом(Shield Stun)" cost="5700" min_level="28"/>
			<skill id="45" level="3" name="Святое Лечение(Divine Heal)" cost="5700" min_level="28"/>
			<skill id="28" level="7" name="Агрессия(Aggression)" cost="11000" min_level="30"/>
			<skill id="217" level="5" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="11000" min_level="30"/>
			<skill id="232" level="10" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="11000" min_level="30"/>
			<skill id="70" level="8" name="Кража Здоровья(Drain HP)" cost="11000" min_level="30"/>
			<skill id="147" level="9" name="Магическое Сопротивление(Magic Resistance)" cost="11000" min_level="30"/>
			<skill id="92" level="10" name="Оглушение Щитом(Shield Stun)" cost="11000" min_level="30"/>
			<skill id="45" level="4" name="Святое Лечение(Divine Heal)" cost="11000" min_level="30"/>
			<skill id="28" level="8" name="Агрессия(Aggression)" cost="11000" min_level="31"/>
			<skill id="232" level="11" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="11000" min_level="31"/>
			<skill id="70" level="9" name="Кража Здоровья(Drain HP)" cost="11000" min_level="31"/>
			<skill id="147" level="10" name="Магическое Сопротивление(Magic Resistance)" cost="11000" min_level="31"/>
			<skill id="92" level="11" name="Оглушение Щитом(Shield Stun)" cost="11000" min_level="31"/>
			<skill id="45" level="5" name="Святое Лечение(Divine Heal)" cost="11000" min_level="31"/>
			<skill id="28" level="9" name="Агрессия(Aggression)" cost="11000" min_level="32"/>
			<skill id="217" level="6" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="11000" min_level="32"/>
			<skill id="232" level="12" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="11000" min_level="32"/>
			<skill id="70" level="10" name="Кража Здоровья(Drain HP)" cost="11000" min_level="32"/>
			<skill id="147" level="11" name="Магическое Сопротивление(Magic Resistance)" cost="11000" min_level="32"/>
			<skill id="92" level="12" name="Оглушение Щитом(Shield Stun)" cost="11000" min_level="32"/>
			<skill id="112" level="2" name="Отклонить Стрелу(Deflect Arrow)" cost="11000" min_level="32"/>
			<skill id="45" level="6" name="Святое Лечение(Divine Heal)" cost="11000" min_level="32"/>
			<skill id="28" level="10" name="Агрессия(Aggression)" cost="20000" min_level="34"/>
			<skill id="217" level="7" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="20000" min_level="34"/>
			<skill id="232" level="13" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="20000" min_level="34"/>
			<skill id="70" level="11" name="Кража Здоровья(Drain HP)" cost="20000" min_level="34"/>
			<skill id="147" level="12" name="Магическое Сопротивление(Magic Resistance)" cost="20000" min_level="34"/>
			<skill id="92" level="13" name="Оглушение Щитом(Shield Stun)" cost="20000" min_level="34"/>
			<skill id="45" level="7" name="Святое Лечение(Divine Heal)" cost="20000" min_level="34"/>
			<skill id="28" level="11" name="Агрессия(Aggression)" cost="20000" min_level="35"/>
			<skill id="232" level="14" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="20000" min_level="35"/>
			<skill id="70" level="12" name="Кража Здоровья(Drain HP)" cost="20000" min_level="35"/>
			<skill id="147" level="13" name="Магическое Сопротивление(Magic Resistance)" cost="20000" min_level="35"/>
			<skill id="92" level="14" name="Оглушение Щитом(Shield Stun)" cost="20000" min_level="35"/>
			<skill id="45" level="8" name="Святое Лечение(Divine Heal)" cost="20000" min_level="35"/>
			<skill id="28" level="12" name="Агрессия(Aggression)" cost="20000" min_level="36"/>
			<skill id="217" level="8" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="20000" min_level="36"/>
			<skill id="232" level="15" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="20000" min_level="36"/>
			<skill id="70" level="13" name="Кража Здоровья(Drain HP)" cost="20000" min_level="36"/>
			<skill id="147" level="14" name="Магическое Сопротивление(Magic Resistance)" cost="20000" min_level="36"/>
			<skill id="92" level="15" name="Оглушение Щитом(Shield Stun)" cost="20000" min_level="36"/>
			<skill id="45" level="9" name="Святое Лечение(Divine Heal)" cost="20000" min_level="36"/>
			<skill id="191" level="1" name="Фокусировка Разума(Focus Mind)" cost="20000" min_level="36"/>
		</class>
	</normal_skill_tree>
</list>

=== dorocki228/test/gameserver/src/dist/data/skill_tree/normal_skill_tree/[53] dwarven_fighter.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--AUTHOR: Bonux-->
<list>
	<normal_skill_tree>
		<class id="53">	<!--Подмастерье-->
			<skill id="194" level="1" name="Везение(Lucky)" min_level="1"/>
			<skill id="1321" level="1" name="Ремесло Гномов(Dwarven Craft)" min_level="1" race="DWARF"/>
			<skill id="142" level="1" name="Владение Броней(Armor Mastery)" cost="15" min_level="5"/>
			<skill id="141" level="1" name="Владение Оружием(Weapon Mastery)" cost="15" min_level="5"/>
			<skill id="254" level="1" name="Оценка(Spoil)" cost="15" min_level="5"/>
			<skill id="42" level="1" name="Присвоение(Sweeper)" cost="15" min_level="5"/>
			<skill id="172" level="1" name="Создать Предмет(Create Item)" cost="15" min_level="5" race="DWARF"/>
			<skill id="142" level="2" name="Владение Броней(Armor Mastery)" cost="100" min_level="8"/>
			<skill id="142" level="3" name="Владение Броней(Armor Mastery)" cost="100" min_level="10"/>
			<skill id="141" level="2" name="Владение Оружием(Weapon Mastery)" cost="100" min_level="10"/>
			<skill id="150" level="1" name="Лимит Веса(Weight Limit)" cost="100" min_level="10"/>
			<skill id="142" level="4" name="Владение Броней(Armor Mastery)" cost="400" min_level="13"/>
			<skill id="142" level="5" name="Владение Броней(Armor Mastery)" cost="400" min_level="15"/>
			<skill id="141" level="3" name="Владение Оружием(Weapon Mastery)" cost="400" min_level="15"/>
			<skill id="239" level="1" name="Квалификация D(Expertise D)" min_level="20"/>
			<skill id="239" level="2" name="Квалификация C(Expertise C)" min_level="40"/>
			<skill id="239" level="3" name="Квалификация B(Expertise B)" min_level="52"/>
			<skill id="239" level="4" name="Квалификация A(Expertise A)" min_level="61"/>
			<skill id="239" level="5" name="Квалификация S(Expertise S)" min_level="76"/>
		</class>
	</normal_skill_tree>
</list>

=== dorocki228/test/gameserver/dist/data/skill_tree/normal_skill_tree/[091] hell_knight.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "../tree.dtd">
<list>
	<normal_skill_tree>
		<class id="91"> <!--Рыцарь Ада-->
            <skill id="58221" level="15" name="Deadly Strike" cost="220000" min_level="79"/>

            <skill id="1322" level="1" name="Common Craft" cost="0" min_level="1"/>
            <skill id="1320" level="10" name="Common Craft Passive" cost="0" min_level="1"/>
            <skill id="246" level="1" name="Печать" cost="0" min_level="1"/>
            <skill id="6088" level="1" name="Блок Бафф" cost="0" min_level="1"/>
            <skill id="28" level="50" name="Агрессия(Aggression)" cost="5400000" min_level="76"/>
            <skill id="984" level="16" name="Атака Щитом(Shield Strike)" cost="5400000" min_level="76"/>
            <skill id="18" level="38" name="Аура Ненависти(Aggression Aura)" cost="5400000" min_level="76"/>
            <skill id="1405" level="3" name="Божественное Вдохновение(Divine Inspiration)" cost="5400000"
                   min_level="76"/>
            <skill id="1405" level="4" name="Божественное Вдохновение(Divine Inspiration)" cost="5400000"
                   min_level="76"/>
			<skill id="217" level="46" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="5400000" min_level="76"/>
			<skill id="232" level="53" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="5400000" min_level="76"/>
			<skill id="70" level="54" name="Кража Здоровья(Drain HP)" cost="5400000" min_level="76"/>
			<skill id="147" level="52" name="Магическое Сопротивление(M. Def.)" cost="5400000" min_level="76"/>
			<skill id="92" level="53" name="Оглушение Щитом(Shield Stun)" cost="5400000" min_level="76"/>
			<skill id="1833" level="1" name="Оседлать Золотого Льва(Mount Golden Lion)" cost="0" min_level="76"/>
			<skill id="46" level="16" name="Отделение Жизни(Life Scavenge)" cost="5400000" min_level="76"/>
			<skill id="335" level="1" name="Стойкость(Toughness)" cost="5400000" min_level="76"/>
			<skill id="127" level="15" name="Увечье(Hamstring)" cost="5400000" min_level="76"/>
			<skill id="65" level="14" name="Ужас(Horror)" cost="5400000" min_level="76"/>
			<skill id="10015" level="1" name="Цепной Удар(Chain Strike)" cost="5400000" min_level="76"/>
			<skill id="28" level="51" name="Агрессия(Aggression)" cost="5400000" min_level="77"/>
			<skill id="984" level="17" name="Атака Щитом(Shield Strike)" cost="5400000" min_level="77"/>
			<skill id="18" level="39" name="Аура Ненависти(Aggression Aura)" cost="5400000" min_level="77"/>
			<skill id="217" level="47" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="5400000" min_level="77"/>
			<skill id="232" level="54" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="5400000" min_level="77"/>
			<skill id="70" level="55" name="Кража Здоровья(Drain HP)" cost="5400000" min_level="77"/>
			<skill id="147" level="53" name="Магическое Сопротивление(M. Def.)" cost="5400000" min_level="77"/>
			<skill id="368" level="1" name="Мщение(Vengeance)" cost="5400000" min_level="77"/>
			<skill id="92" level="54" name="Оглушение Щитом(Shield Stun)" cost="5400000" min_level="77"/>
			<skill id="913" level="1" name="Отклонить Магию(Deflect Magic)" cost="5400000" min_level="77"/>
			<skill id="28" level="52" name="Агрессия(Aggression)" cost="12600000" min_level="78"/>
			<skill id="984" level="18" name="Атака Щитом(Shield Strike)" cost="12600000" min_level="78"/>
			<skill id="18" level="40" name="Аура Ненависти(Aggression Aura)" cost="12600000" min_level="78"/>
			<skill id="217" level="48" name="Владение Мечом / Дробящим Оружием(Sword/Blunt Weapon Mastery)" cost="12600000" min_level="78"/>
			<skill id="232" level="55" name="Владение Тяжелой Броней(Heavy Armor Mastery)" cost="12600000" min_level="78"/>
			<skill id="70" level="56" name="Кража Здоровья(Drain HP)" cost="12600000" min_level="78"/>
			<skill id="147" level="54" name="Магическое Сопротивление(M. Def.)" cost="12600000" min_level="78"/>
			<skill id="92" level="55" name="Оглушение Щитом(Shield Stun)" cost="12600000" min_level="78"/>
			<skill id="46" level="17" name="Отделение Жизни(Life Scavenge)" cost="12600000" min_level="78"/>
			<skill id="283" level="8" name="Призвать Темную Пантеру(Summon Dark Panther)" cost="12600000" min_level="78"/>
			<skill id="342" level="1" name="Прикосновение Смерти(Touch of Death)" cost="12600000" min_level="78"/>
			<skill id="429" level="1" name="Рыцарство(Knighthood)" cost="12600000" min_level="78"/>
			<skill id="103" level="5" name="Трупная Чума(Corpse Plague)" cost="12600000" min_level="78"/>
			<skill id="127" level="16" name="Увечье(Hamstring)" cost="12600000" min_level="78"/>
			<skill id="65" level="15" name="Ужас(Horror)" cost="12600000" min_level="78"/>
			<skill id="528" level="1" name="Щит Веры(Shield of Faith)" cost="12600000" min_level="79"/>
			<skill id="762" level="1" name="Безумный Сокрушитель(Insane Crusher)" cost="12600000" min_level="80"/>
			<skill id="15689" level="1" name="Mass Chain Strike" cost="12600000" min_level="80"/>
		</class>
	</normal_skill_tree>
</list>
